export const menuData = [
  {
    id: 1,
    name: "Medhu Vada",
    type: "Snacks",
    image:
      "https://img.freepik.com/free-photo/brunch-lunch-homemade-donuts-sprinkled-with-powdered-sugar_2829-11276.jpg",
    price: 2.0,
    originalPrice: 2.5,
    rating: 4.6,
    reviewCount: 180,
    description:
      "Crispy deep-fried lentil donuts with a soft center, served with coconut chutney.",
    ingredients: [
      "Urad dal",
      "Black pepper",
      "Cumin seeds",
      "Ginger",
      "Curry leaves",
      "Salt",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "15-20 mins",
    calories: 120,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Dessert",
    tags: ["Crispy", "Spiral", "Sweet syrup"],
    allergens: ["Gluten", "Dairy"],
    portion: "3 pieces",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "4g",
      carbs: "38g",
      fat: "6g",
      fiber: "1g",
    },
  },
  {
    id: 68,
    name: "Ras Malai",
    type: "Dessert",
    image:
      "https://img.freepik.com/free-photo/still-life-sweet-tang-yuan-arrangement_23-2149149071.jpg",
    price: 5.0,
    originalPrice: 6.5,
    rating: 4.6,
    reviewCount: 280,
    description: "Soft cottage cheese dumplings in sweetened milk.",
    ingredients: [
      "Paneer",
      "Milk",
      "Sugar",
      "Cardamom",
      "Pistachios",
      "Almonds",
    ],
    dietary: ["Vegetarian"],
    spiceLevel: "None",
    preparationTime: "25-30 mins",
    calories: 240,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Dessert",
    tags: ["Cottage cheese", "Milk", "Rich"],
    allergens: ["Dairy", "Tree nuts"],
    portion: "2 pieces",
    chef: "Chef Rajesh",
    nutritionalInfo: {
      protein: "12g",
      carbs: "32g",
      fat: "10g",
      fiber: "1g",
    },
  },
  {
    id: 69,
    name: "Gulab Jamun",
    type: "Dessert",
    image:
      "https://img.freepik.com/free-photo/flat-lay-indian-dessert-assortment_23-2149312344.jpg",
    price: 2.0,
    originalPrice: 2.5,
    rating: 4.7,
    reviewCount: 420,
    description: "Deep-fried milk dumplings soaked in rose-flavored syrup.",
    ingredients: [
      "Milk powder",
      "Flour",
      "Ghee",
      "Sugar",
      "Rose water",
      "Cardamom",
    ],
    dietary: ["Vegetarian"],
    spiceLevel: "None",
    preparationTime: "20-25 mins",
    calories: 220,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Dessert",
    tags: ["Milk dumplings", "Rose syrup", "Classic"],
    allergens: ["Dairy", "Gluten"],
    portion: "2 pieces",
    chef: "Chef Rajesh",
    nutritionalInfo: {
      protein: "6g",
      carbs: "38g",
      fat: "8g",
      fiber: "1g",
    },
  },
  {
    id: 70,
    name: "Cake",
    type: "Dessert",
    image:
      "https://img.freepik.com/free-photo/high-angle-cakes-plate-with-macarons_23-2148489104.jpg",
    price: 2.0,
    originalPrice: 3.0,
    rating: 4.1,
    reviewCount: 150,
    description: "Assorted cake slices - chocolate, vanilla, or fruit.",
    ingredients: [
      "Flour",
      "Sugar",
      "Eggs",
      "Butter",
      "Baking powder",
      "Flavoring",
    ],
    dietary: ["Vegetarian"],
    spiceLevel: "None",
    preparationTime: "5-8 mins",
    calories: 280,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Dessert",
    tags: ["Cake", "Assorted flavors", "Western"],
    allergens: ["Gluten", "Dairy", "Eggs"],
    portion: "1 slice",
    chef: "Chef Maria",
    nutritionalInfo: {
      protein: "5g",
      carbs: "45g",
      fat: "12g",
      fiber: "2g",
    },
  },
  {
    id: 71,
    name: "Fruit Salad",
    type: "Dessert",
    image:
      "https://img.freepik.com/free-photo/colorful-fruit-salad-bowl_23-2148196331.jpg",
    price: 4.0,
    originalPrice: 5.0,
    rating: 4.2,
    reviewCount: 180,
    description: "Fresh seasonal fruits with honey and mint.",
    ingredients: ["Mixed seasonal fruits", "Honey", "Mint", "Lemon juice"],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "None",
    preparationTime: "8-10 mins",
    calories: 120,
    isAvailable: true,
    isRecommended: true,
    isPopular: false,
    category: "Dessert",
    tags: ["Fresh", "Healthy", "Seasonal"],
    allergens: [],
    portion: "1 bowl",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "2g",
      carbs: "30g",
      fat: "1g",
      fiber: "5g",
    },
  },
  {
    id: 2,
    name: "Dal Vada",
    type: "Snacks",
    image:
      "https://img.freepik.com/premium-photo/kachori-is-spicy-snack-from-india-also-spelled-as-kachauri-kachodi-served-with-tomato-ketchup-favorite-tea-time-snacks_54391-2917.jpg",
    price: 2.0,
    originalPrice: 2.5,
    rating: 4.4,
    reviewCount: 156,
    description: "Golden fried lentil fritters with aromatic spices and herbs.",
    ingredients: [
      "Chana dal",
      "Onion",
      "Green chili",
      "Ginger",
      "Coriander leaves",
      "Salt",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "12-15 mins",
    calories: 110,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "South Indian",
    tags: ["Crispy", "Lentil", "Spiced"],
    allergens: [],
    portion: "3 pieces",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "7g",
      carbs: "14g",
      fat: "5g",
      fiber: "3g",
    },
  },
  {
    id: 3,
    name: "Onion Vada",
    type: "Snacks",
    image:
      "https://img.freepik.com/free-photo/high-angle-delicious-jewish-dish_23-2148814457.jpg",
    price: 2.0,
    originalPrice: 2.5,
    rating: 4.3,
    reviewCount: 142,
    description:
      "Crispy onion fritters with lentil flour and traditional spices.",
    ingredients: [
      "Onion",
      "Chickpea flour",
      "Rice flour",
      "Green chili",
      "Ginger",
      "Curry leaves",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "10-12 mins",
    calories: 95,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "South Indian",
    tags: ["Onion", "Crispy", "Street food"],
    allergens: [],
    portion: "4 pieces",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "4g",
      carbs: "16g",
      fat: "4g",
      fiber: "2g",
    },
  },
  {
    id: 4,
    name: "Veg. Samosa",
    type: "Snacks",
    image:
      "https://img.freepik.com/free-photo/high-angle-plate-with-pakistani-food_23-2148825158.jpg",
    price: 2.0,
    originalPrice: 2.5,
    rating: 4.5,
    reviewCount: 320,
    description:
      "Triangular pastry filled with spiced potatoes and vegetables.",
    ingredients: [
      "Potato",
      "Green peas",
      "Pastry flour",
      "Cumin",
      "Coriander",
      "Garam masala",
    ],
    dietary: ["Vegetarian"],
    spiceLevel: "Mild",
    preparationTime: "15-18 mins",
    calories: 150,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "North Indian",
    tags: ["Pastry", "Fried", "Classic"],
    allergens: ["Gluten"],
    portion: "2 pieces",
    chef: "Chef Rajesh",
    nutritionalInfo: {
      protein: "5g",
      carbs: "24g",
      fat: "8g",
      fiber: "3g",
    },
  },
  {
    id: 5,
    name: "Egg Puffs",
    type: "Snacks",
    image:
      "https://img.freepik.com/free-photo/fresh-pastry-wooden-background_78826-2271.jpg",
    price: 2.5,
    originalPrice: 2.5,
    rating: 4.7,
    reviewCount: 290,
    description: "Flaky puff pastry filled with spiced boiled egg curry.",
    ingredients: [
      "Eggs",
      "Puff pastry",
      "Onion",
      "Tomato",
      "Spices",
      "Curry leaves",
    ],
    dietary: ["Non-vegetarian"],
    spiceLevel: "Medium",
    preparationTime: "20-25 mins",
    calories: 180,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Egg", "Pastry", "Spiced"],
    allergens: ["Gluten", "Eggs"],
    portion: "1 piece",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "12g",
      carbs: "18g",
      fat: "10g",
      fiber: "1g",
    },
  },
  {
    id: 6,
    name: "Chicken Puffs",
    type: "Snacks",
    image:
      "https://img.freepik.com/free-photo/chicken-pie-kurnik-that-is-beautifully-decorated-table_1150-23100.jpg",
    price: 3.5,
    originalPrice: 3.0,
    rating: 4.8,
    reviewCount: 450,
    description: "Golden puff pastry stuffed with spicy chicken curry filling.",
    ingredients: [
      "Chicken",
      "Puff pastry",
      "Onion",
      "Ginger-garlic",
      "Spices",
      "Coriander",
    ],
    dietary: ["Non-vegetarian"],
    spiceLevel: "Medium",
    preparationTime: "25-30 mins",
    calories: 220,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Chicken", "Pastry", "Spicy"],
    allergens: ["Gluten"],
    portion: "1 piece",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "18g",
      carbs: "20g",
      fat: "12g",
      fiber: "1g",
    },
  },
  {
    id: 7,
    name: "Chicken Cutlet",
    type: "Snacks",
    image:
      "https://img.freepik.com/free-photo/side-view-stuffed-chicken-roll-cherry-tomatoes_141793-5123.jpg",
    price: 3.0,
    originalPrice: 4.0,
    rating: 4.6,
    reviewCount: 210,
    description: "Crispy breaded chicken patties with aromatic spices.",
    ingredients: [
      "Minced chicken",
      "Breadcrumbs",
      "Egg",
      "Onion",
      "Spices",
      "Herbs",
    ],
    dietary: ["Non-vegetarian"],
    spiceLevel: "Medium",
    preparationTime: "18-22 mins",
    calories: 260,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Anglo-Indian",
    tags: ["Crispy", "Chicken", "Breaded"],
    allergens: ["Gluten", "Eggs"],
    portion: "2 pieces",
    chef: "Chef Maria",
    nutritionalInfo: {
      protein: "22g",
      carbs: "15g",
      fat: "14g",
      fiber: "1g",
    },
  },
  {
    id: 8,
    name: "Pathiri",
    type: "Snacks",
    image:
      "https://img.freepik.com/free-photo/fried-qutabs-with-dried-berries_140725-4018.jpg",
    price: 2.0,
    originalPrice: 3.5,
    rating: 4.4,
    reviewCount: 95,
    description: "Thin rice pancakes, a traditional Malabar delicacy.",
    ingredients: ["Rice flour", "Water", "Salt", "Coconut oil"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "None",
    preparationTime: "15-20 mins",
    calories: 140,
    isAvailable: true,
    isRecommended: true,
    isPopular: false,
    category: "Malabar",
    tags: ["Rice", "Traditional", "Pancake"],
    allergens: [],
    portion: "3 pieces",
    chef: "Chef Fathima",
    nutritionalInfo: {
      protein: "3g",
      carbs: "30g",
      fat: "2g",
      fiber: "2g",
    },
  },
  {
    id: 9,
    name: "Pazham Pori",
    type: "Snacks",
    image:
      "https://img.freepik.com/free-photo/top-view-yummy-rolled-pancakes-with-bananas-dark-background-cake-dough-hotcake-color-meal-pastry-sweet-pie-meat-free-space_179666-46847.jpg",
    price: 2.0,
    originalPrice: 2.5,
    rating: 4.5,
    reviewCount: 275,
    description: "Sweet banana fritters coated in spiced flour batter.",
    ingredients: [
      "Ripe banana",
      "All-purpose flour",
      "Rice flour",
      "Turmeric",
      "Salt",
      "Sugar",
    ],
    dietary: ["Vegetarian"],
    spiceLevel: "None",
    preparationTime: "10-12 mins",
    calories: 130,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Sweet", "Banana", "Fritter"],
    allergens: ["Gluten"],
    portion: "4 pieces",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "3g",
      carbs: "28g",
      fat: "3g",
      fiber: "2g",
    },
  },
  {
    id: 10,
    name: "Fried Rice",
    type: "Rice",
    image:
      "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=300&fit=crop&crop=center",
    price: 6.0,
    originalPrice: 7.0,
    rating: 4.3,
    reviewCount: 380,
    description: "Wok-fried rice with vegetables and aromatic sauces.",
    ingredients: [
      "Basmati rice",
      "Mixed vegetables",
      "Soy sauce",
      "Garlic",
      "Ginger",
      "Spring onion",
    ],
    dietary: ["Vegetarian"],
    spiceLevel: "Mild",
    preparationTime: "15-18 mins",
    calories: 320,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "Indo-Chinese",
    tags: ["Rice", "Stir-fried", "Vegetables"],
    allergens: ["Soy"],
    portion: "1 plate",
    chef: "Chef Wong",
    nutritionalInfo: {
      protein: "8g",
      carbs: "65g",
      fat: "6g",
      fiber: "4g",
    },
  },
  {
    id: 11,
    name: "Fried Rice Chicken Roast",
    type: "Rice",
    image:
      "https://img.freepik.com/free-photo/dried-squid-baked-with-sweet-sour-sauce-asian-seafood-concept_1150-23607.jpg",
    price: 12.0,
    originalPrice: 14.0,
    rating: 4.7,
    reviewCount: 520,
    description: "Fried rice served with spicy roasted chicken pieces.",
    ingredients: [
      "Basmati rice",
      "Chicken",
      "Vegetables",
      "Soy sauce",
      "Spices",
      "Herbs",
    ],
    dietary: ["Non-vegetarian"],
    spiceLevel: "Medium",
    preparationTime: "25-30 mins",
    calories: 480,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Indo-Chinese",
    tags: ["Rice", "Chicken", "Combo"],
    allergens: ["Soy"],
    portion: "1 plate",
    chef: "Chef Wong",
    nutritionalInfo: {
      protein: "32g",
      carbs: "58g",
      fat: "14g",
      fiber: "3g",
    },
  },
  {
    id: 12,
    name: "Biriyani Rice",
    type: "Rice",
    image:
      "https://img.freepik.com/free-photo/top-view-pakistan-meal-assortment_23-2148821514.jpg",
    price: 6.0,
    originalPrice: 7.0,
    rating: 4.4,
    reviewCount: 285,
    description: "Fragrant basmati rice cooked with aromatic spices and herbs.",
    ingredients: [
      "Basmati rice",
      "Saffron",
      "Cardamom",
      "Bay leaves",
      "Cinnamon",
      "Cloves",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "35-40 mins",
    calories: 290,
    isAvailable: true,
    isRecommended: true,
    isPopular: false,
    category: "Biriyani",
    tags: ["Aromatic", "Basmati", "Spiced"],
    allergens: [],
    portion: "1 plate",
    chef: "Chef Abdul",
    nutritionalInfo: {
      protein: "6g",
      carbs: "62g",
      fat: "4g",
      fiber: "2g",
    },
  },
  {
    id: 13,
    name: "Pulavu Rice",
    type: "Rice",
    image:
      "https://images.unsplash.com/photo-1664717698774-84f62382613b?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 6.0,
    originalPrice: 7.0,
    rating: 4.2,
    reviewCount: 165,
    description: "Mildly spiced rice cooked with whole spices and ghee.",
    ingredients: [
      "Basmati rice",
      "Ghee",
      "Whole spices",
      "Onion",
      "Mint",
      "Coriander",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "30-35 mins",
    calories: 310,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "North Indian",
    tags: ["Ghee", "Aromatic", "Spiced"],
    allergens: ["Dairy"],
    portion: "1 plate",
    chef: "Chef Rajesh",
    nutritionalInfo: {
      protein: "7g",
      carbs: "58g",
      fat: "8g",
      fiber: "2g",
    },
  },
  {
    id: 14,
    name: "Ghee Rice",
    type: "Rice",
    image:
      "https://img.freepik.com/free-photo/top-view-rice-rice-dried-fruits-plate-bowls-spices-tree-branches_140725-78779.jpg",
    price: 6.0,
    originalPrice: 7.0,
    rating: 4.6,
    reviewCount: 420,
    description: "Fragrant rice cooked in pure ghee with aromatic spices.",
    ingredients: [
      "Basmati rice",
      "Pure ghee",
      "Cardamom",
      "Cinnamon",
      "Cloves",
      "Bay leaves",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "None",
    preparationTime: "25-30 mins",
    calories: 340,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "South Indian",
    tags: ["Ghee", "Fragrant", "Simple"],
    allergens: ["Dairy"],
    portion: "1 plate",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "6g",
      carbs: "55g",
      fat: "12g",
      fiber: "1g",
    },
  },
  {
    id: 15,
    name: "Chicken Biriyani",
    type: "Biriyani Dishes",
    image:
      "https://img.freepik.com/free-photo/indian-traditional-dish-with-rice-cashew-nuts-sauce-lemon-vegetables-coriander-leaf-wooden-tray_613910-21742.jpg",
    price: 10.0,
    originalPrice: 12.0,
    rating: 4.8,
    reviewCount: 850,
    description:
      "Aromatic basmati rice layered with spiced chicken and cooked to perfection.",
    ingredients: [
      "Chicken",
      "Basmati rice",
      "Saffron",
      "Yogurt",
      "Onion",
      "Spices",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "45-60 mins",
    calories: 520,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Biriyani",
    tags: ["Chicken", "Aromatic", "Layered"],
    allergens: ["Dairy"],
    portion: "1 plate",
    chef: "Chef Abdul",
    nutritionalInfo: {
      protein: "35g",
      carbs: "68g",
      fat: "18g",
      fiber: "3g",
    },
  },
  {
    id: 16,
    name: "Malabar Chicken Biriyani",
    type: "Biriyani Dishes",
    image:
      "https://img.freepik.com/free-photo/khan-pilav-with-various-fruits-inside_140725-1802.jpg",
    price: 12.0,
    originalPrice: 14.0,
    rating: 4.9,
    reviewCount: 620,
    description:
      "Traditional Malabar-style biriyani with unique spice blend and coconut.",
    ingredients: [
      "Chicken",
      "Jeera rice",
      "Coconut",
      "Malabar spices",
      "Cashews",
      "Raisins",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "60-75 mins",
    calories: 580,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Malabar",
    tags: ["Malabar", "Traditional", "Coconut"],
    allergens: ["Tree nuts", "Dairy"],
    portion: "1 plate",
    chef: "Chef Fathima",
    nutritionalInfo: {
      protein: "38g",
      carbs: "72g",
      fat: "22g",
      fiber: "4g",
    },
  },
  {
    id: 17,
    name: "Kappa Biriyani",
    type: "Biriyani Dishes",
    image:
      "https://img.freepik.com/free-photo/delicious-goulash-ready-dinner_23-2149370863.jpg",
    price: 10.0,
    originalPrice: 12.0,
    rating: 4.5,
    reviewCount: 180,
    description:
      "Unique biriyani made with tapioca instead of rice, Kerala style.",
    ingredients: [
      "Tapioca",
      "Chicken",
      "Coconut",
      "Curry leaves",
      "Spices",
      "Coconut oil",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "40-50 mins",
    calories: 450,
    isAvailable: true,
    isRecommended: true,
    isPopular: false,
    category: "Kerala",
    tags: ["Unique", "Tapioca", "Kerala"],
    allergens: [],
    portion: "1 plate",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "28g",
      carbs: "58g",
      fat: "16g",
      fiber: "6g",
    },
  },
  {
    id: 18,
    name: "Kerala Veg. Meals",
    type: "Kerala Meals",
    image:
      "https://img.freepik.com/free-photo/arrangement-different-pakistan-goodies_23-2148821571.jpg",
    price: 10.0,
    originalPrice: 12.0,
    rating: 4.4,
    reviewCount: 220,
    description:
      "Traditional Kerala vegetarian meal served on banana leaf with multiple curries.",
    ingredients: [
      "Rice",
      "Sambar",
      "Rasam",
      "Vegetable curry",
      "Pickle",
      "Papad",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "30-40 mins",
    calories: 480,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Traditional", "Complete meal", "Banana leaf"],
    allergens: [],
    portion: "1 full meal",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "18g",
      carbs: "88g",
      fat: "12g",
      fiber: "15g",
    },
  },
  {
    id: 19,
    name: "Kerala Fish Curry Meals",
    type: "Kerala Meals",
    image:
      "https://images.unsplash.com/photo-1678781416302-d59ed9ed46d0?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 15.0,
    originalPrice: 17.0,
    rating: 4.7,
    reviewCount: 480,
    description:
      "Authentic Kerala meal with fish curry, rice, and traditional sides.",
    ingredients: [
      "Fish",
      "Coconut curry",
      "Rice",
      "Vegetable sides",
      "Pickle",
      "Papad",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "35-45 mins",
    calories: 550,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Fish curry", "Complete meal", "Coconut"],
    allergens: ["Fish"],
    portion: "1 full meal",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "32g",
      carbs: "68g",
      fat: "18g",
      fiber: "8g",
    },
  },
  {
    id: 20,
    name: "Kerala Beef Fry Meals",
    type: "Kerala Meals",
    image:
      "https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=400&h=300&fit=crop&crop=center",
    price: 15.0,
    originalPrice: 17.0,
    rating: 4.6,
    reviewCount: 340,
    description:
      "Traditional Kerala meal featuring spicy beef fry with rice and sides.",
    ingredients: [
      "Beef",
      "Coconut",
      "Spices",
      "Rice",
      "Vegetable sides",
      "Pickle",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Hot",
    preparationTime: "45-60 mins",
    calories: 620,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Beef fry", "Spicy", "Complete meal"],
    allergens: [],
    portion: "1 full meal",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "42g",
      carbs: "55g",
      fat: "25g",
      fiber: "6g",
    },
  },
  {
    id: 21,
    name: "Chicken Roast",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/roast-chicken-with-red-wine-sauce_1203-9214.jpg",
    price: 10.0,
    originalPrice: 12.0,
    rating: 4.7,
    reviewCount: 420,
    description: "Spicy roasted chicken with Kerala spices and coconut.",
    ingredients: [
      "Chicken",
      "Coconut",
      "Curry leaves",
      "Spices",
      "Onion",
      "Ginger-garlic",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "30-35 mins",
    calories: 380,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Roasted", "Spicy", "Coconut"],
    allergens: [],
    portion: "4-5 pieces",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "45g",
      carbs: "8g",
      fat: "18g",
      fiber: "2g",
    },
  },
  {
    id: 22,
    name: "Chicken Liver Roast",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/fried-chicken-liver-with-onions-herbs_2829-19702.jpg",
    price: 10.0,
    originalPrice: 12.0,
    rating: 4.3,
    reviewCount: 165,
    description: "Spicy roasted chicken liver with traditional Kerala spices.",
    ingredients: [
      "Chicken liver",
      "Onion",
      "Spices",
      "Curry leaves",
      "Coconut oil",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Hot",
    preparationTime: "20-25 mins",
    calories: 280,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Kerala",
    tags: ["Liver", "Spicy", "Traditional"],
    allergens: [],
    portion: "1 plate",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "32g",
      carbs: "6g",
      fat: "12g",
      fiber: "1g",
    },
  },
  {
    id: 23,
    name: "Chicken Manjoorian",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/front-view-tasty-fried-chicken-with-fresh-vegetables-seasonings-dark-space_140725-79494.jpg",
    price: 12.0,
    originalPrice: 14.0,
    rating: 4.5,
    reviewCount: 280,
    description:
      "Indo-Chinese style chicken in sweet and sour sauce with vegetables.",
    ingredients: [
      "Chicken",
      "Bell peppers",
      "Onion",
      "Soy sauce",
      "Tomato sauce",
      "Cornflour",
    ],
    dietary: ["Non-vegetarian"],
    spiceLevel: "Medium",
    preparationTime: "25-30 mins",
    calories: 420,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Indo-Chinese",
    tags: ["Sweet and sour", "Sauce", "Vegetables"],
    allergens: ["Soy", "Gluten"],
    portion: "1 plate",
    chef: "Chef Wong",
    nutritionalInfo: {
      protein: "38g",
      carbs: "22g",
      fat: "16g",
      fiber: "3g",
    },
  },
  {
    id: 24,
    name: "Beef Roast",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/delicious-goulash-ready-dinner_23-2149370851.jpg",
    price: 14.0,
    originalPrice: 16.0,
    rating: 4.8,
    reviewCount: 520,
    description: "Traditional Kerala beef roast with coconut and spices.",
    ingredients: [
      "Beef",
      "Coconut",
      "Curry leaves",
      "Garam masala",
      "Onion",
      "Ginger",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Hot",
    preparationTime: "45-60 mins",
    calories: 480,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Beef", "Roasted", "Spicy"],
    allergens: [],
    portion: "1 plate",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "42g",
      carbs: "8g",
      fat: "28g",
      fiber: "2g",
    },
  },
  {
    id: 25,
    name: "Beef Fry",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/djiz-byz-traditional-dish-liver-heart-potato-greens-top-view_141793-4407.jpg",
    price: 14.0,
    originalPrice: 16.0,
    rating: 4.7,
    reviewCount: 480,
    description: "Crispy fried beef pieces with aromatic Kerala spices.",
    ingredients: [
      "Beef",
      "Coconut oil",
      "Curry leaves",
      "Shallots",
      "Spices",
      "Coconut",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Hot",
    preparationTime: "40-50 mins",
    calories: 450,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Fried", "Crispy", "Spicy"],
    allergens: [],
    portion: "1 plate",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "40g",
      carbs: "6g",
      fat: "26g",
      fiber: "1g",
    },
  },
  {
    id: 26,
    name: "Egg Roast",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/baked-meatballs-chicken-fillet-tomato-sauce_2829-11139.jpg",
    price: 6.0,
    originalPrice: 16.0,
    rating: 4.4,
    reviewCount: 320,
    description: "Hard-boiled eggs in spicy tomato and onion gravy.",
    ingredients: [
      "Eggs",
      "Tomato",
      "Onion",
      "Coconut milk",
      "Curry leaves",
      "Spices",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "20-25 mins",
    calories: 280,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "Kerala",
    tags: ["Egg", "Gravy", "Tomato"],
    allergens: ["Eggs"],
    portion: "4 eggs",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "24g",
      carbs: "12g",
      fat: "18g",
      fiber: "3g",
    },
  },
  {
    id: 27,
    name: "Duck Roast",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/top-view-bowl-homemade-stew-pepper_23-2148494757.jpg",
    price: 12.0,
    originalPrice: 14.0,
    rating: 4.6,
    reviewCount: 210,
    description: "Tender duck roasted with traditional Kerala spices.",
    ingredients: [
      "Duck",
      "Coconut",
      "Curry leaves",
      "Spices",
      "Onion",
      "Tomato",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "50-60 mins",
    calories: 520,
    isAvailable: true,
    isRecommended: true,
    isPopular: false,
    category: "Kerala",
    tags: ["Duck", "Roasted", "Traditional"],
    allergens: [],
    portion: "4-5 pieces",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "38g",
      carbs: "8g",
      fat: "32g",
      fiber: "2g",
    },
  },
  {
    id: 28,
    name: "Fish Curry",
    type: "Curry",
    image:
      "https://images.unsplash.com/photo-1654863404432-cac67587e25d?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 10.0,
    originalPrice: 12.0,
    rating: 4.8,
    reviewCount: 620,
    description:
      "Traditional Kerala fish curry in coconut milk with curry leaves.",
    ingredients: [
      "Fish",
      "Coconut milk",
      "Tamarind",
      "Curry leaves",
      "Spices",
      "Onion",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "25-30 mins",
    calories: 320,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Fish", "Curry", "Coconut milk"],
    allergens: ["Fish"],
    portion: "4-5 pieces",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "28g",
      carbs: "8g",
      fat: "18g",
      fiber: "2g",
    },
  },
  {
    id: 29,
    name: "Fish Fry",
    type: "Curry",
    image:
      "https://images.unsplash.com/photo-1673436977947-0787164a9abc?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 10.0,
    originalPrice: 12.0,
    rating: 4.7,
    reviewCount: 450,
    description: "Crispy fried fish marinated in Kerala spices.",
    ingredients: [
      "Fish",
      "Turmeric",
      "Chili powder",
      "Ginger-garlic",
      "Curry leaves",
      "Oil",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "20-25 mins",
    calories: 380,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Fish", "Fried", "Crispy"],
    allergens: ["Fish"],
    portion: "4-5 pieces",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "32g",
      carbs: "4g",
      fat: "22g",
      fiber: "1g",
    },
  },
  {
    id: 30,
    name: "Karimeen Fry",
    type: "Curry",
    image:
      "https://images.unsplash.com/photo-1665401015549-712c0dc5ef85?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 12.0,
    originalPrice: 16.0,
    rating: 4.9,
    reviewCount: 380,
    description: "Pearl spot fish marinated and fried to perfection.",
    ingredients: [
      "Karimeen fish",
      "Spices",
      "Turmeric",
      "Coconut oil",
      "Curry leaves",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "25-30 mins",
    calories: 420,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Karimeen", "Pearl spot", "Fried"],
    allergens: ["Fish"],
    portion: "1 whole fish",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "35g",
      carbs: "3g",
      fat: "24g",
      fiber: "0g",
    },
  },
  {
    id: 31,
    name: "Veg Curry",
    type: "Curry",
    image:
      "https://plus.unsplash.com/premium_photo-1700752343880-fa224237af07?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 6.0,
    originalPrice: 8.0,
    rating: 4.3,
    reviewCount: 240,
    description: "Mixed vegetable curry in coconut milk with Kerala spices.",
    ingredients: [
      "Mixed vegetables",
      "Coconut milk",
      "Curry leaves",
      "Spices",
      "Coconut oil",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "20-25 mins",
    calories: 180,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Kerala",
    tags: ["Vegetables", "Curry", "Coconut"],
    allergens: [],
    portion: "1 bowl",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "6g",
      carbs: "18g",
      fat: "12g",
      fiber: "8g",
    },
  },
  {
    id: 32,
    name: "Gopi Manjoorian",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/vertical-shot-chickpea-curry-chana-masala-with-lime-bowl-white-surf_181624-31989.jpg",
    price: 8.0,
    originalPrice: 10.0,
    rating: 4.2,
    reviewCount: 120,
    description: "Cauliflower in Indo-Chinese sweet and sour sauce.",
    ingredients: [
      "Cauliflower",
      "Bell peppers",
      "Soy sauce",
      "Tomato sauce",
      "Cornflour",
    ],
    dietary: ["Vegetarian"],
    spiceLevel: "Medium",
    preparationTime: "20-25 mins",
    calories: 220,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Indo-Chinese",
    tags: ["Cauliflower", "Sweet and sour", "Sauce"],
    allergens: ["Soy", "Gluten"],
    portion: "1 plate",
    chef: "Chef Wong",
    nutritionalInfo: {
      protein: "8g",
      carbs: "28g",
      fat: "10g",
      fiber: "6g",
    },
  },
  {
    id: 33,
    name: "Veg Salad",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/top-view-tasty-salad-with-vegetables_23-2148515491.jpg",
    price: 10.0,
    originalPrice: 12.0,
    rating: 4.0,
    reviewCount: 85,
    description: "Fresh mixed vegetable salad with lemon dressing.",
    ingredients: ["Cucumber", "Tomato", "Onion", "Carrot", "Lemon", "Herbs"],
    dietary: ["Vegetarian", "Gluten-free", "Vegan"],
    spiceLevel: "None",
    preparationTime: "10-12 mins",
    calories: 80,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Healthy",
    tags: ["Fresh", "Salad", "Healthy"],
    allergens: [],
    portion: "1 bowl",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "3g",
      carbs: "18g",
      fat: "1g",
      fiber: "6g",
    },
  },
  {
    id: 34,
    name: "Appam & Chicken Roast",
    type: "Kerala Specials",
    image:
      "https://www.yummyoyummy.com/wp-content/uploads/2019/12/DSC_1277.jpg",
    price: 12.0,
    originalPrice: 14.0,
    rating: 4.8,
    reviewCount: 520,
    description:
      "Soft fermented rice pancakes served with spicy chicken roast.",
    ingredients: ["Rice", "Coconut milk", "Chicken", "Spices", "Curry leaves"],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "25-30 mins",
    calories: 480,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Appam", "Chicken", "Combo"],
    allergens: [],
    portion: "3 appams + curry",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "32g",
      carbs: "45g",
      fat: "18g",
      fiber: "3g",
    },
  },
  {
    id: 35,
    name: "Appam & Beef Fry",
    type: "Kerala Specials",
    image: "https://i.redd.it/yz7v00jq1yo51.jpg",
    price: 14.0,
    originalPrice: 16.0,
    rating: 4.7,
    reviewCount: 420,
    description: "Traditional appam served with spicy Kerala beef fry.",
    ingredients: ["Rice", "Coconut milk", "Beef", "Spices", "Coconut"],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Hot",
    preparationTime: "30-35 mins",
    calories: 540,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Appam", "Beef", "Spicy"],
    allergens: [],
    portion: "3 appams + curry",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "35g",
      carbs: "42g",
      fat: "24g",
      fiber: "3g",
    },
  },
  {
    id: 36,
    name: "Appam & Duck Roast",
    type: "Kerala Specials",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/05/Topdown_shot_of_Palappam_with_duck_curry.jpg",
    price: 14.0,
    originalPrice: 16.0,
    rating: 4.6,
    reviewCount: 280,
    description: "Soft appam paired with aromatic duck roast.",
    ingredients: ["Rice", "Coconut milk", "Duck", "Spices", "Curry leaves"],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "35-40 mins",
    calories: 580,
    isAvailable: true,
    isRecommended: true,
    isPopular: false,
    category: "Kerala",
    tags: ["Appam", "Duck", "Roasted"],
    allergens: [],
    portion: "3 appams + curry",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "36g",
      carbs: "44g",
      fat: "28g",
      fiber: "3g",
    },
  },
  {
    id: 37,
    name: "Porotta & Chicken Roast",
    type: "Kerala Specials",
    image:
      "https://i.ytimg.com/vi/ypEWQZBq-yo/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAABmrdEyeyA48xljx8Tm2Kz2hZyQ",
    price: 12.0,
    originalPrice: 14.0,
    rating: 4.7,
    reviewCount: 680,
    description: "Flaky layered bread served with spicy chicken roast.",
    ingredients: ["Flour", "Ghee", "Chicken", "Spices", "Onion"],
    dietary: ["Non-vegetarian"],
    spiceLevel: "Medium",
    preparationTime: "25-30 mins",
    calories: 520,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Porotta", "Chicken", "Layered bread"],
    allergens: ["Gluten", "Dairy"],
    portion: "2 parottas + curry",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "34g",
      carbs: "48g",
      fat: "22g",
      fiber: "2g",
    },
  },
  {
    id: 38,
    name: "Porotta & Beef Roast/Fry",
    type: "Kerala Specials",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkea2QZiAofHX0_0yAKQb7dzspAv-VzybOrg&s",
    price: 14.0,
    originalPrice: 16.0,
    rating: 4.8,
    reviewCount: 720,
    description: "Crispy porotta with choice of beef roast or beef fry.",
    ingredients: ["Flour", "Ghee", "Beef", "Spices", "Coconut"],
    dietary: ["Non-vegetarian"],
    spiceLevel: "Hot",
    preparationTime: "30-35 mins",
    calories: 580,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Porotta", "Beef", "Choice"],
    allergens: ["Gluten", "Dairy"],
    portion: "2 parottas + curry",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "38g",
      carbs: "46g",
      fat: "26g",
      fiber: "2g",
    },
  },
  {
    id: 39,
    name: "Porotta & Channa Dal",
    type: "Kerala Specials",
    image:
      "https://images.picxy.com/cache/2021/4/7/ce65006e269397c79b8e53feef105315.jpg",
    price: 10.0,
    originalPrice: 16.0,
    rating: 4.4,
    reviewCount: 180,
    description: "Soft porotta served with spiced chickpea curry.",
    ingredients: ["Flour", "Ghee", "Chickpeas", "Tomato", "Onion", "Spices"],
    dietary: ["Vegetarian"],
    spiceLevel: "Medium",
    preparationTime: "25-30 mins",
    calories: 420,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Kerala",
    tags: ["Porotta", "Chickpeas", "Vegetarian"],
    allergens: ["Gluten", "Dairy"],
    portion: "2 parottas + curry",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "18g",
      carbs: "65g",
      fat: "14g",
      fiber: "12g",
    },
  },
  {
    id: 40,
    name: "Chola Battura",
    type: "Kerala Specials",
    image:
      "https://i.ytimg.com/vi/csfIOfMnRGg/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLB6GPMx72TdT-BQh86wkTA3VKBRpQ",
    price: 10.0,
    originalPrice: 12.0,
    rating: 4.5,
    reviewCount: 350,
    description: "Spicy chickpea curry served with deep-fried bread.",
    ingredients: ["Chickpeas", "Flour", "Yogurt", "Spices", "Tomato", "Onion"],
    dietary: ["Vegetarian"],
    spiceLevel: "Medium",
    preparationTime: "30-35 mins",
    calories: 450,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "North Indian",
    tags: ["Chickpeas", "Deep-fried bread", "Spicy"],
    allergens: ["Gluten", "Dairy"],
    portion: "2 bhature + curry",
    chef: "Chef Rajesh",
    nutritionalInfo: {
      protein: "16g",
      carbs: "68g",
      fat: "16g",
      fiber: "10g",
    },
  },
  {
    id: 41,
    name: "Kappa Fish Curry",
    type: "Kerala Specials",
    image:
      "https://lh3.ggpht.com/_OGMa3JuKVTk/TZ4dyUgrEtI/AAAAAAAAF-M/Ce65ZDpiPWU/DSC_1402_thumb%5B8%5D.jpg?imgmax=800",
    price: 12.0,
    originalPrice: 12.0,
    rating: 4.6,
    reviewCount: 420,
    description: "Boiled tapioca served with traditional fish curry.",
    ingredients: ["Tapioca", "Fish", "Coconut milk", "Curry leaves", "Spices"],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "30-35 mins",
    calories: 380,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Tapioca", "Fish curry", "Traditional"],
    allergens: ["Fish"],
    portion: "1 plate",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "24g",
      carbs: "52g",
      fat: "12g",
      fiber: "6g",
    },
  },
  {
    id: 42,
    name: "Kappa Potty",
    type: "Kerala Specials",
    image:
      "https://b.zmtcdn.com/data/dish_photos/fdd/17027f9177f52f9bd8db399f8e7e0fdd.png",
    price: 14.0,
    originalPrice: 14.0,
    rating: 4.3,
    reviewCount: 160,
    description: "Mashed tapioca with coconut and spices.",
    ingredients: [
      "Tapioca",
      "Coconut",
      "Shallots",
      "Green chili",
      "Curry leaves",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "25-30 mins",
    calories: 320,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Kerala",
    tags: ["Tapioca", "Mashed", "Coconut"],
    allergens: [],
    portion: "1 plate",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "4g",
      carbs: "58g",
      fat: "8g",
      fiber: "6g",
    },
  },
  {
    id: 43,
    name: "Kappa Beef Roast/Fry",
    type: "Kerala Specials",
    image: "https://i.ytimg.com/vi/Bv0Vl3cr11g/hqdefault.jpg",
    price: 14.0,
    originalPrice: 16.0,
    rating: 4.7,
    reviewCount: 380,
    description: "Tapioca served with choice of beef roast or beef fry.",
    ingredients: ["Tapioca", "Beef", "Coconut", "Spices", "Curry leaves"],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Hot",
    preparationTime: "35-40 mins",
    calories: 520,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala",
    tags: ["Tapioca", "Beef", "Choice"],
    allergens: [],
    portion: "1 plate",
    chef: "Chef Suresh",
    nutritionalInfo: {
      protein: "32g",
      carbs: "48g",
      fat: "22g",
      fiber: "6g",
    },
  },
  {
    id: 44,
    name: "Masala Dosa",
    type: "South Varieties",
    image:
      "https://www.mydelicious-recipes.com/home/images/120_1080_1080/mydelicious-recipes-masala-dosa-with-batter",
    price: 10.0,
    originalPrice: 12.0,
    rating: 4.6,
    reviewCount: 520,
    description: "Crispy rice crepe filled with spiced potato masala.",
    ingredients: [
      "Rice",
      "Urad dal",
      "Potato",
      "Onion",
      "Spices",
      "Curry leaves",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "15-20 mins",
    calories: 280,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "South Indian",
    tags: ["Crepe", "Potato filling", "Crispy"],
    allergens: [],
    portion: "1 dosa",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "8g",
      carbs: "52g",
      fat: "6g",
      fiber: "4g",
    },
  },
  {
    id: 45,
    name: "Ghee Roast",
    type: "South Varieties",
    image:
      "https://www.qasralbaharshj.com/wp-content/uploads/2024/11/GheeRoast_1-600x600.webp",
    price: 10.0,
    originalPrice: 12.0,
    rating: 4.5,
    reviewCount: 320,
    description: "Crispy dosa roasted in pure ghee with special spices.",
    ingredients: ["Rice", "Urad dal", "Pure ghee", "Red chili paste", "Spices"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "15-20 mins",
    calories: 320,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "South Indian",
    tags: ["Ghee", "Roasted", "Spicy"],
    allergens: ["Dairy"],
    portion: "1 dosa",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "8g",
      carbs: "48g",
      fat: "12g",
      fiber: "3g",
    },
  },
  {
    id: 46,
    name: "Paneer Masala Dosa",
    type: "South Varieties",
    image:
      "https://www.carveyourcraving.com/wp-content/uploads/2018/08/paneer-masala-for-dosa-recipe-blog.jpg",
    price: 14.0,
    originalPrice: 16.0,
    rating: 4.4,
    reviewCount: 280,
    description: "Crispy dosa filled with spiced paneer and potato masala.",
    ingredients: ["Rice", "Urad dal", "Paneer", "Potato", "Spices", "Onion"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "18-22 mins",
    calories: 380,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "South Indian",
    tags: ["Paneer", "Protein", "Filling"],
    allergens: ["Dairy"],
    portion: "1 dosa",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "18g",
      carbs: "52g",
      fat: "14g",
      fiber: "4g",
    },
  },
  {
    id: 47,
    name: "Mysore Masala Dosa",
    type: "South Varieties",
    image:
      "https://i.pinimg.com/736x/2a/c1/51/2ac15169850a766390adcba3a6d28eef.jpg",
    price: 14.0,
    originalPrice: 16.0,
    rating: 4.6,
    reviewCount: 420,
    description: "Spicy Mysore-style dosa with red chutney and potato filling.",
    ingredients: [
      "Rice",
      "Urad dal",
      "Red chutney",
      "Potato",
      "Spices",
      "Garlic",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Hot",
    preparationTime: "18-22 mins",
    calories: 340,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "South Indian",
    tags: ["Mysore style", "Spicy", "Red chutney"],
    allergens: [],
    portion: "1 dosa",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "10g",
      carbs: "58g",
      fat: "8g",
      fiber: "5g",
    },
  },
  {
    id: 48,
    name: "Egg Dosa",
    type: "South Varieties",
    image:
      "https://thumbs.dreamstime.com/b/delicious-masala-dosa-sides-vibrant-generated-ai-south-indian-crepe-filled-spiced-potatoes-vegetables-served-383817116.jpg",
    price: 12.0,
    originalPrice: 16.0,
    rating: 4.5,
    reviewCount: 380,
    description: "Crispy dosa topped with beaten egg and spices.",
    ingredients: [
      "Rice",
      "Urad dal",
      "Egg",
      "Onion",
      "Green chili",
      "Coriander",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "15-18 mins",
    calories: 360,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "South Indian",
    tags: ["Egg", "Protein", "Crispy"],
    allergens: ["Eggs"],
    portion: "1 dosa",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "18g",
      carbs: "48g",
      fat: "12g",
      fiber: "3g",
    },
  },
  {
    id: 49,
    name: "Thattu Dosa",
    type: "South Varieties",
    image: "https://i.ytimg.com/vi/t0vCNQvZBDE/sddefault.jpg",
    price: 8.0,
    originalPrice: 14.0,
    rating: 4.3,
    reviewCount: 185,
    description: "Small thick dosas served as a set with chutneys.",
    ingredients: [
      "Rice",
      "Urad dal",
      "Coconut chutney",
      "Sambar",
      "Tomato chutney",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "12-15 mins",
    calories: 240,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "South Indian",
    tags: ["Small", "Set", "Traditional"],
    allergens: [],
    portion: "4 pieces",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "8g",
      carbs: "45g",
      fat: "5g",
      fiber: "4g",
    },
  },
  {
    id: 50,
    name: "Onion Uthappam",
    type: "South Varieties",
    image:
      "https://revi.b-cdn.net/wp-content/uploads/2015/05/onion-uttapam-vert.jpg",
    price: 10.0,
    originalPrice: 10.0,
    rating: 4.4,
    reviewCount: 290,
    description: "Thick pancake topped with onions and spices.",
    ingredients: [
      "Rice",
      "Urad dal",
      "Onion",
      "Green chili",
      "Coriander",
      "Curry leaves",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "12-15 mins",
    calories: 220,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "South Indian",
    tags: ["Thick pancake", "Onion", "Spiced"],
    allergens: [],
    portion: "1 uthappam",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "7g",
      carbs: "42g",
      fat: "4g",
      fiber: "3g",
    },
  },
  {
    id: 51,
    name: "Cheese Uthappam",
    type: "South Varieties",
    image:
      "https://thanjaigroup.com/thanjairestaurant/wp-content/uploads/2021/08/Uthappam-Article-2.jpg",
    price: 14.0,
    originalPrice: 12.0,
    rating: 4.2,
    reviewCount: 210,
    description: "Thick pancake topped with cheese and vegetables.",
    ingredients: ["Rice", "Urad dal", "Cheese", "Onion", "Tomato", "Capsicum"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "15-18 mins",
    calories: 320,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "South Indian",
    tags: ["Cheese", "Vegetables", "Fusion"],
    allergens: ["Dairy"],
    portion: "1 uthappam",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "14g",
      carbs: "38g",
      fat: "12g",
      fiber: "3g",
    },
  },
  {
    id: 52,
    name: "Idli Sambar",
    type: "South Varieties",
    image:
      "https://sapanarestaurant.com/wp-content/uploads/2019/11/idli-sambar-900x600.jpg",
    price: 6.0,
    originalPrice: 8.0,
    rating: 4.5,
    reviewCount: 450,
    description: "Steamed rice cakes served with lentil curry.",
    ingredients: [
      "Rice",
      "Urad dal",
      "Toor dal",
      "Vegetables",
      "Tamarind",
      "Spices",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "10-12 mins",
    calories: 180,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "South Indian",
    tags: ["Steamed", "Healthy", "Light"],
    allergens: [],
    portion: "3 idlis + sambar",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "8g",
      carbs: "35g",
      fat: "2g",
      fiber: "6g",
    },
  },
  {
    id: 53,
    name: "Vada Sambar",
    type: "South Varieties",
    image:
      "https://vegecravings.com/wp-content/uploads/2018/02/Medu-Vada-Recipe-Step-By-Step-Instructions.jpg",
    price: 6.0,
    originalPrice: 8.0,
    rating: 4.4,
    reviewCount: 320,
    description: "Crispy lentil donuts served with spiced lentil curry.",
    ingredients: ["Urad dal", "Toor dal", "Vegetables", "Tamarind", "Spices"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "12-15 mins",
    calories: 220,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "South Indian",
    tags: ["Crispy", "Lentil", "Traditional"],
    allergens: [],
    portion: "2 vadas + sambar",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "12g",
      carbs: "28g",
      fat: "8g",
      fiber: "8g",
    },
  },
  {
    id: 54,
    name: "Tea",
    type: "Drinks",
    image:
      "https://www.munatycooking.com/wp-content/uploads/2024/04/Three-glasses-filled-with-karak-chai.jpg",
    price: 2.0,
    originalPrice: 2.5,
    rating: 4.2,
    reviewCount: 280,
    description: "Traditional Indian tea brewed with milk and sugar.",
    ingredients: ["Tea leaves", "Milk", "Sugar", "Water"],
    dietary: ["Vegetarian"],
    spiceLevel: "None",
    preparationTime: "5-8 mins",
    calories: 60,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "Beverages",
    tags: ["Hot", "Traditional", "Milk tea"],
    allergens: ["Dairy"],
    portion: "1 cup",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "2g",
      carbs: "12g",
      fat: "2g",
      fiber: "0g",
    },
  },
  {
    id: 55,
    name: "Masala Tea",
    type: "Drinks",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNz8svxz897FnF-0oqyIHQwbB8VUS0-doVIQ&s",
    price: 3.0,
    originalPrice: 3.5,
    rating: 4.5,
    reviewCount: 420,
    description: "Spiced tea with cardamom, ginger, and aromatic spices.",
    ingredients: [
      "Tea leaves",
      "Milk",
      "Sugar",
      "Cardamom",
      "Ginger",
      "Spices",
    ],
    dietary: ["Vegetarian"],
    spiceLevel: "Mild",
    preparationTime: "8-10 mins",
    calories: 70,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Beverages",
    tags: ["Spiced", "Aromatic", "Traditional"],
    allergens: ["Dairy"],
    portion: "1 cup",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "2g",
      carbs: "14g",
      fat: "2g",
      fiber: "0g",
    },
  },
  {
    id: 56,
    name: "Cardamom Tea",
    type: "Drinks",
    image:
      "https://cdn.shopify.com/s/files/1/0573/8502/5710/articles/a-spicy-cup-of-goodness-how-cardamom-in-tea-boosts-your-well-being-226252.jpg?v=1736821845",
    price: 3.0,
    originalPrice: 3.5,
    rating: 4.3,
    reviewCount: 180,
    description: "Fragrant tea infused with cardamom pods.",
    ingredients: ["Tea leaves", "Milk", "Sugar", "Cardamom pods"],
    dietary: ["Vegetarian"],
    spiceLevel: "None",
    preparationTime: "8-10 mins",
    calories: 65,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Beverages",
    tags: ["Cardamom", "Fragrant", "Aromatic"],
    allergens: ["Dairy"],
    portion: "1 cup",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "2g",
      carbs: "13g",
      fat: "2g",
      fiber: "0g",
    },
  },
  {
    id: 57,
    name: "Bru Coffee",
    type: "Drinks",
    image:
      "https://cdn.shopify.com/s/files/1/0918/3414/files/perfect-cup-black-coffee.jpg?v=1498751612",
    price: 3.0,
    originalPrice: 3.5,
    rating: 4.1,
    reviewCount: 220,
    description: "Strong black coffee served hot.",
    ingredients: ["Coffee beans", "Sugar", "Water"],
    dietary: ["Vegetarian", "Vegan"],
    spiceLevel: "None",
    preparationTime: "5-8 mins",
    calories: 20,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "Beverages",
    tags: ["Black coffee", "Strong", "Caffeine"],
    allergens: [],
    portion: "1 cup",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "0g",
      carbs: "5g",
      fat: "0g",
      fiber: "0g",
    },
  },
  {
    id: 58,
    name: "Mango Lassi",
    type: "Drinks",
    image:
      "https://aroundtheyum.com/wp-content/uploads/2024/09/mango-lassi-recipe.jpg",
    price: 3.0,
    originalPrice: 4.0,
    rating: 4.6,
    reviewCount: 380,
    description: "Creamy yogurt drink blended with fresh mango.",
    ingredients: ["Mango", "Yogurt", "Sugar", "Cardamom", "Ice"],
    dietary: ["Vegetarian"],
    spiceLevel: "None",
    preparationTime: "5-8 mins",
    calories: 180,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Beverages",
    tags: ["Mango", "Creamy", "Refreshing"],
    allergens: ["Dairy"],
    portion: "1 glass",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "6g",
      carbs: "32g",
      fat: "4g",
      fiber: "2g",
    },
  },
  {
    id: 59,
    name: "Fresh Lime",
    type: "Drinks",
    image:
      "https://cdn.healthyrecipes101.com/recipes/images/juices/fresh-lime-juice-recipe-clannw7eo00kfpw1b79na4lsu.webp?w=1080&q=80",
    price: 3.0,
    originalPrice: 3.5,
    rating: 4.3,
    reviewCount: 250,
    description: "Fresh lime juice with sugar and mint.",
    ingredients: ["Fresh lime", "Sugar", "Mint", "Salt", "Water", "Ice"],
    dietary: ["Vegetarian", "Vegan"],
    spiceLevel: "None",
    preparationTime: "5-8 mins",
    calories: 40,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "Beverages",
    tags: ["Fresh", "Lime", "Refreshing"],
    allergens: [],
    portion: "1 glass",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "0g",
      carbs: "10g",
      fat: "0g",
      fiber: "0g",
    },
  },
  {
    id: 60,
    name: "Sharjah Shake",
    type: "Drinks",
    image:
      "https://thephotowali.wordpress.com/wp-content/uploads/2018/04/fb_img_1523868519864-011008790977.jpeg",
    price: 4.0,
    originalPrice: 5.0,
    rating: 4.4,
    reviewCount: 180,
    description: "Rich milkshake with nuts and dry fruits.",
    ingredients: ["Milk", "Almonds", "Cashews", "Dates", "Sugar", "Ice cream"],
    dietary: ["Vegetarian"],
    spiceLevel: "None",
    preparationTime: "8-10 mins",
    calories: 280,
    isAvailable: true,
    isRecommended: true,
    isPopular: false,
    category: "Beverages",
    tags: ["Rich", "Nuts", "Milkshake"],
    allergens: ["Dairy", "Tree nuts"],
    portion: "1 glass",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "12g",
      carbs: "38g",
      fat: "14g",
      fiber: "3g",
    },
  },
  {
    id: 61,
    name: "Vanilla Shake",
    type: "Drinks",
    image:
      "https://www.allrecipes.com/thmb/uzxCGTc-5WCUZnZ7BUcYcmWKxjo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AR-48974-vanilla-milkshake-hero-4x3-c815295c714f41f6b17b104e7403a53b.jpg",
    price: 4.0,
    originalPrice: 5.0,
    rating: 4.2,
    reviewCount: 220,
    description: "Creamy vanilla milkshake with ice cream.",
    ingredients: ["Milk", "Vanilla ice cream", "Sugar", "Vanilla extract"],
    dietary: ["Vegetarian"],
    spiceLevel: "None",
    preparationTime: "5-8 mins",
    calories: 250,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "Beverages",
    tags: ["Vanilla", "Creamy", "Ice cream"],
    allergens: ["Dairy"],
    portion: "1 glass",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "8g",
      carbs: "42g",
      fat: "8g",
      fiber: "0g",
    },
  },
  {
    id: 62,
    name: "Fizzy Drinks",
    type: "Drinks",
    image: "https://i.redd.it/yyr6vtruhzbb1.jpg",
    price: 2.5,
    originalPrice: 3.0,
    rating: 3.8,
    reviewCount: 150,
    description: "Assorted carbonated soft drinks.",
    ingredients: ["Carbonated water", "Sugar", "Flavoring", "Preservatives"],
    dietary: ["Vegetarian", "Vegan"],
    spiceLevel: "None",
    preparationTime: "2-3 mins",
    calories: 140,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "Beverages",
    tags: ["Carbonated", "Soft drink", "Fizzy"],
    allergens: [],
    portion: "1 bottle/can",
    chef: "N/A",
    nutritionalInfo: {
      protein: "0g",
      carbs: "38g",
      fat: "0g",
      fiber: "0g",
    },
  },
  {
    id: 63,
    name: "Water",
    type: "Drinks",
    image:
      "https://www.seriouseats.com/thmb/CfZJlOxychcWqMRUIBGIhy3CtfU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20240401-SEA-TasteTests-AmandaSuarez-00-e7b924fdd6f4410596841e9531377ee6.jpg",
    price: 2.0,
    originalPrice: 2.5,
    rating: 4.0,
    reviewCount: 100,
    description: "Pure drinking water.",
    ingredients: ["Water"],
    dietary: ["Vegetarian", "Vegan"],
    spiceLevel: "None",
    preparationTime: "1-2 mins",
    calories: 0,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Beverages",
    tags: ["Pure", "Hydration", "Basic"],
    allergens: [],
    portion: "1 bottle",
    chef: "N/A",
    nutritionalInfo: {
      protein: "0g",
      carbs: "0g",
      fat: "0g",
      fiber: "0g",
    },
  },
  {
    id: 64,
    name: "Payasam",
    type: "Dessert",
    image:
      "https://vismaifood.com/storage/app/uploads/public/44e/993/010/thumb__700_0_0_0_auto.jpg",
    price: 2.0,
    originalPrice: 6.0,
    rating: 4.7,
    reviewCount: 320,
    description:
      "Traditional Kerala rice pudding with coconut milk and jaggery.",
    ingredients: [
      "Rice",
      "Coconut milk",
      "Jaggery",
      "Cardamom",
      "Cashews",
      "Raisins",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "None",
    preparationTime: "30-40 mins",
    calories: 220,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Dessert",
    tags: ["Traditional", "Rice pudding", "Sweet"],
    allergens: ["Tree nuts"],
    portion: "1 bowl",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "6g",
      carbs: "42g",
      fat: "8g",
      fiber: "2g",
    },
  },
  {
    id: 65,
    name: "Mango Pudding",
    type: "Dessert",
    image:
      "https://takestwoeggs.com/wp-content/uploads/2022/06/Mango-Pudding-Takestwoeggs-Final-Photography-sq.jpg",
    price: 2.0,
    originalPrice: 3.0,
    rating: 4.4,
    reviewCount: 180,
    description: "Creamy mango pudding with fresh mango pieces.",
    ingredients: ["Mango", "Milk", "Sugar", "Gelatin", "Cream"],
    dietary: ["Vegetarian"],
    spiceLevel: "None",
    preparationTime: "15-20 mins",
    calories: 160,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "Dessert",
    tags: ["Mango", "Creamy", "Fruity"],
    allergens: ["Dairy"],
    portion: "1 cup",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "4g",
      carbs: "32g",
      fat: "4g",
      fiber: "1g",
    },
  },
  {
    id: 66,
    name: "Ladu",
    type: "Dessert",
    image: "https://static.toiimg.com/thumb/55048059.cms?width=1200&height=900",
    price: 2.0,
    originalPrice: 2.5,
    rating: 4.5,
    reviewCount: 250,
    description: "Sweet round balls made with flour, ghee, and sugar.",
    ingredients: ["Chickpea flour", "Ghee", "Sugar", "Cardamom", "Nuts"],
    dietary: ["Vegetarian"],
    spiceLevel: "None",
    preparationTime: "20-25 mins",
    calories: 180,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Dessert",
    tags: ["Traditional", "Sweet balls", "Ghee"],
    allergens: ["Dairy", "Tree nuts"],
    portion: "2 pieces",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "6g",
      carbs: "28g",
      fat: "8g",
      fiber: "2g",
    },
  },
  {
    id: 67,
    name: "Chocolate Cake",
    type: "Dessert",
    image:
      "https://www.indianhealthyrecipes.com/wp-content/uploads/2024/06/classic-chocolate-cake-recipe.jpg",
    price: 2.0,
    originalPrice: 4.0,
    rating: 4.6,
    reviewCount: 400,
    description: "Rich chocolate cake with creamy frosting.",
    ingredients: [
      "Flour",
      "Cocoa powder",
      "Sugar",
      "Butter",
      "Eggs",
      "Chocolate",
    ],
    dietary: ["Vegetarian"],
    spiceLevel: "None",
    preparationTime: "30-35 mins",
    calories: 350,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Dessert",
    tags: ["Chocolate", "Cake", "Rich"],
    allergens: ["Dairy", "Eggs", "Gluten"],
    portion: "1 slice",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "6g",
      carbs: "50g",
      fat: "14g",
      fiber: "2g",
    },
  },
];
