const menuData = [
  {
    id: 1,
    name: "Medhu Vada",
    type: "Snacks",
    image:
      "https://img.freepik.com/free-photo/brunch-lunch-homemade-donuts-sprinkled-with-powdered-sugar_2829-11276.jpg",
    price: 2.0,
    rating: 4.6,
    reviewCount: 180,
    description:
      "Crispy deep-fried lentil donuts with a soft center, served with coconut chutney.",
    category: "Snacks",
  },
  {
    id: 68,
    name: "Ras Malai",
    type: "Dessert",
    image:
      "https://img.freepik.com/free-photo/still-life-sweet-tang-yuan-arrangement_23-2149149071.jpg",
    price: 5.0,
    rating: 4.6,
    reviewCount: 95,
    description: "Soft cottage cheese dumplings in sweetened milk.",
    category: "Dessert",
  },
  {
    id: 69,
    name: "Gulab Jamun",
    type: "Dessert",
    image:
      "https://img.freepik.com/free-photo/flat-lay-indian-dessert-assortment_23-2149312344.jpg",
    price: 2.0,
    rating: 4.7,
    reviewCount: 158,
    description: "Deep-fried milk dumplings soaked in rose-flavored syrup.",
    category: "Dessert",
  },
  {
    id: 70,
    name: "Cake",
    type: "Dessert",
    image:
      "https://img.freepik.com/free-photo/high-angle-cakes-plate-with-macarons_23-2148489104.jpg",
    price: 2.0,
    rating: 4.1,
    reviewCount: 72,
    description: "Assorted cake slices - chocolate, vanilla, or fruit.",
    category: "Dessert",
  },
  {
    id: 71,
    name: "Fruit Salad",
    type: "Dessert",
    image:
      "https://img.freepik.com/free-photo/colorful-fruit-salad-bowl_23-2148196331.jpg",
    price: 4.0,
    rating: 4.2,
    reviewCount: 89,
    description: "Fresh seasonal fruits with honey and mint.",
    category: "Dessert",
  },
  {
    id: 2,
    name: "Dal Vada",
    type: "Snacks",
    image:
      "https://img.freepik.com/premium-photo/kachori-is-spicy-snack-from-india-also-spelled-as-kachauri-kachodi-served-with-tomato-ketchup-favorite-tea-time-snacks_54391-2917.jpg",
    price: 2.0,
    rating: 4.4,
    reviewCount: 123,
    description: "Golden fried lentil fritters with aromatic spices and herbs.",
    category: "Snacks",
  },
  {
    id: 3,
    name: "Onion Vada",
    type: "Snacks",
    image:
      "https://img.freepik.com/free-photo/high-angle-delicious-jewish-dish_23-2148814457.jpg",
    price: 2.0,
    rating: 4.3,
    reviewCount: 142,
    description:
      "Crispy onion fritters with lentil flour and traditional spices.",
    category: "Snacks",
  },
  {
    id: 4,
    name: "Veg. Samosa",
    type: "Snacks",
    image:
      "https://img.freepik.com/free-photo/high-angle-plate-with-pakistani-food_23-2148825158.jpg",
    price: 2.0,
    rating: 4.5,
    reviewCount: 320,
    description:
      "Triangular pastry filled with spiced potatoes and vegetables.",
    category: "Snacks",
  },
  {
    id: 5,
    name: "Egg Puffs",
    type: "Snacks",
    image:
      "https://img.freepik.com/free-photo/fresh-pastry-wooden-background_78826-2271.jpg",
    price: 2.5,
    rating: 4.7,
    reviewCount: 201,
    description: "Flaky puff pastry filled with spiced boiled egg curry.",
    category: "Snacks",
  },
  {
    id: 6,
    name: "Chicken Puffs",
    type: "Snacks",
    image:
      "https://img.freepik.com/free-photo/chicken-pie-kurnik-that-is-beautifully-decorated-table_1150-23100.jpg",
    price: 3.5,
    rating: 4.8,
    reviewCount: 267,
    description: "Golden puff pastry stuffed with spicy chicken curry filling.",
    category: "Snacks",
  },
  {
    id: 7,
    name: "Chicken Cutlet",
    type: "Snacks",
    image:
      "https://img.freepik.com/free-photo/side-view-stuffed-chicken-roll-cherry-tomatoes_141793-5123.jpg",
    price: 3.0,
    rating: 4.6,
    reviewCount: 145,
    description: "Crispy breaded chicken patties with aromatic spices.",
    category: "Snacks",
  },
  {
    id: 8,
    name: "Pathiri",
    type: "Snacks",
    image:
      "https://img.freepik.com/free-photo/fried-qutabs-with-dried-berries_140725-4018.jpg",
    price: 2.0,
    rating: 4.4,
    reviewCount: 98,
    description: "Thin rice pancakes, a traditional Malabar delicacy.",
    category: "Snacks",
  },
  {
    id: 9,
    name: "Pazham Pori",
    type: "Snacks",
    image:
      "https://img.freepik.com/free-photo/top-view-yummy-rolled-pancakes-with-bananas-dark-background-cake-dough-hotcake-color-meal-pastry-sweet-pie-meat-free-space_179666-46847.jpg",
    price: 2.0,
    rating: 4.5,
    reviewCount: 167,
    description: "Sweet banana fritters coated in spiced flour batter.",
    category: "Snacks",
  },
  {
    id: 10,
    name: "Fried Rice",
    type: "Rice",
    image:
      "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=300&fit=crop&crop=center",
    price: 6.0,
    rating: 4.3,
    reviewCount: 156,
    description: "Wok-fried rice with vegetables and aromatic sauces.",
    category: "Rice",
  },
  {
    id: 11,
    name: "Fried Rice Chicken Roast",
    type: "Rice",
    image:
      "https://img.freepik.com/free-photo/dried-squid-baked-with-sweet-sour-sauce-asian-seafood-concept_1150-23607.jpg",
    price: 12.0,
    rating: 4.7,
    reviewCount: 234,
    description: "Fried rice served with spicy roasted chicken pieces.",
    category: "Rice",
  },
  {
    id: 12,
    name: "Biriyani Rice",
    type: "Rice",
    image:
      "https://img.freepik.com/free-photo/top-view-pakistan-meal-assortment_23-2148821514.jpg",
    price: 6.0,
    rating: 4.4,
    reviewCount: 189,
    description: "Fragrant basmati rice cooked with aromatic spices and herbs.",
    category: "Rice",
  },
  {
    id: 13,
    name: "Pulavu Rice",
    type: "Rice",
    image:
      "https://images.unsplash.com/photo-1664717698774-84f62382613b?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 6.0,
    rating: 4.2,
    reviewCount: 112,
    description: "Mildly spiced rice cooked with whole spices and ghee.",
    category: "Rice",
  },
  {
    id: 14,
    name: "Ghee Rice",
    type: "Rice",
    image:
      "https://img.freepik.com/free-photo/top-view-rice-rice-dried-fruits-plate-bowls-spices-tree-branches_140725-78779.jpg",
    price: 6.0,
    rating: 4.6,
    reviewCount: 178,
    description: "Fragrant rice cooked in pure ghee with aromatic spices.",
    category: "Rice",
  },
  {
    id: 15,
    name: "Chicken Biriyani",
    type: "Biriyani Dishes",
    image:
      "https://img.freepik.com/free-photo/indian-traditional-dish-with-rice-cashew-nuts-sauce-lemon-vegetables-coriander-leaf-wooden-tray_613910-21742.jpg",
    price: 10.0,
    rating: 4.8,
    reviewCount: 342,
    description:
      "Aromatic basmati rice layered with spiced chicken and cooked to perfection.",
    category: "Biriyani Dishes",
  },
  {
    id: 16,
    name: "Malabar Chicken Biriyani",
    type: "Biriyani Dishes",
    image:
      "https://img.freepik.com/free-photo/khan-pilav-with-various-fruits-inside_140725-1802.jpg",
    price: 12.0,
    rating: 4.9,
    reviewCount: 298,
    description:
      "Traditional Malabar-style biriyani with unique spice blend and coconut.",
    category: "Biriyani Dishes",
  },
  {
    id: 17,
    name: "Kappa Biriyani",
    type: "Biriyani Dishes",
    image:
      "https://img.freepik.com/free-photo/delicious-goulash-ready-dinner_23-2149370863.jpg",
    price: 10.0,
    rating: 4.5,
    reviewCount: 127,
    description:
      "Unique biriyani made with tapioca instead of rice, Kerala style.",
    category: "Biriyani Dishes",
  },
  {
    id: 18,
    name: "Kerala Veg. Meals",
    type: "Kerala Meals",
    image:
      "https://img.freepik.com/free-photo/arrangement-different-pakistan-goodies_23-2148821571.jpg",
    price: 10.0,
    rating: 4.4,
    reviewCount: 156,
    description:
      "Traditional Kerala vegetarian meal served on banana leaf with multiple curries.",
    category: "Kerala Meals",
  },
  {
    id: 19,
    name: "Kerala Fish Curry Meals",
    type: "Kerala Meals",
    image:
      "https://images.unsplash.com/photo-1678781416302-d59ed9ed46d0?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 15.0,
    rating: 4.7,
    reviewCount: 223,
    description:
      "Authentic Kerala meal with fish curry, rice, and traditional sides.",
    category: "Kerala Meals",
  },
  {
    id: 20,
    name: "Kerala Beef Fry Meals",
    type: "Kerala Meals",
    image:
      "https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=400&h=300&fit=crop&crop=center",
    price: 15.0,
    rating: 4.6,
    reviewCount: 189,
    description:
      "Traditional Kerala meal featuring spicy beef fry with rice and sides.",
    category: "Kerala Meals",
  },
  {
    id: 21,
    name: "Chicken Roast",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/roast-chicken-with-red-wine-sauce_1203-9214.jpg",
    price: 10.0,
    rating: 4.7,
    reviewCount: 267,
    description: "Spicy roasted chicken with Kerala spices and coconut.",
    category: "Curry",
  },
  {
    id: 22,
    name: "Chicken Liver Roast",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/fried-chicken-liver-with-onions-herbs_2829-19702.jpg",
    price: 10.0,
    rating: 4.3,
    reviewCount: 134,
    description: "Spicy roasted chicken liver with traditional Kerala spices.",
    category: "Curry",
  },
  {
    id: 23,
    name: "Chicken Manjoorian",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/front-view-tasty-fried-chicken-with-fresh-vegetables-seasonings-dark-space_140725-79494.jpg",
    price: 12.0,
    rating: 4.5,
    reviewCount: 178,
    description:
      "Indo-Chinese style chicken in sweet and sour sauce with vegetables.",
    category: "Curry",
  },
  {
    id: 24,
    name: "Beef Roast",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/delicious-goulash-ready-dinner_23-2149370851.jpg",
    price: 14.0,
    rating: 4.8,
    reviewCount: 298,
    description: "Traditional Kerala beef roast with coconut and spices.",
    category: "Curry",
  },
  {
    id: 25,
    name: "Beef Fry",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/djiz-byz-traditional-dish-liver-heart-potato-greens-top-view_141793-4407.jpg",
    price: 14.0,
    rating: 4.7,
    reviewCount: 234,
    description: "Crispy fried beef pieces with aromatic Kerala spices.",
    category: "Curry",
  },
  {
    id: 26,
    name: "Egg Roast",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/baked-meatballs-chicken-fillet-tomato-sauce_2829-11139.jpg",
    price: 6.0,
    rating: 4.4,
    reviewCount: 145,
    description: "Hard-boiled eggs in spicy tomato and onion gravy.",
    category: "Curry",
  },
  {
    id: 27,
    name: "Duck Roast",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/top-view-bowl-homemade-stew-pepper_23-2148494757.jpg",
    price: 12.0,
    rating: 4.6,
    reviewCount: 167,
    description: "Tender duck roasted with traditional Kerala spices.",
    category: "Curry",
  },
  {
    id: 28,
    name: "Fish Curry",
    type: "Curry",
    image:
      "https://images.unsplash.com/photo-1654863404432-cac67587e25d?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 10.0,
    rating: 4.8,
    reviewCount: 312,
    description:
      "Traditional Kerala fish curry in coconut milk with curry leaves.",
    category: "Curry",
  },
  {
    id: 29,
    name: "Fish Fry",
    type: "Curry",
    image:
      "https://images.unsplash.com/photo-1673436977947-0787164a9abc?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 10.0,
    rating: 4.7,
    reviewCount: 201,
    description: "Crispy fried fish marinated in Kerala spices.",
    category: "Curry",
  },
  {
    id: 30,
    name: "Karimeen Fry",
    type: "Curry",
    image:
      "https://images.unsplash.com/photo-1665401015549-712c0dc5ef85?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 12.0,
    rating: 4.9,
    reviewCount: 189,
    description: "Pearl spot fish marinated and fried to perfection.",
    category: "Curry",
  },
  {
    id: 31,
    name: "Veg Curry",
    type: "Curry",
    image:
      "https://plus.unsplash.com/premium_photo-1700752343880-fa224237af07?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 6.0,
    rating: 4.3,
    reviewCount: 123,
    description: "Mixed vegetable curry in coconut milk with Kerala spices.",
    category: "Curry",
  },
  {
    id: 32,
    name: "Gopi Manjoorian",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/vertical-shot-chickpea-curry-chana-masala-with-lime-bowl-white-surf_181624-31989.jpg",
    price: 8.0,
    rating: 4.2,
    reviewCount: 89,
    description: "Cauliflower in Indo-Chinese sweet and sour sauce.",
    category: "Curry",
  },
  {
    id: 33,
    name: "Veg Salad",
    type: "Curry",
    image:
      "https://img.freepik.com/free-photo/top-view-tasty-salad-with-vegetables_23-2148515491.jpg",
    price: 10.0,
    rating: 4.0,
    reviewCount: 67,
    description: "Fresh mixed vegetable salad with lemon dressing.",
    category: "Curry",
  },
  {
    id: 34,
    name: "Appam & Chicken Roast",
    type: "Kerala Specials",
    image:
      "https://www.yummyoyummy.com/wp-content/uploads/2019/12/DSC_1277.jpg",
    price: 12.0,
    rating: 4.8,
    reviewCount: 245,
    description:
      "Soft fermented rice pancakes served with spicy chicken roast.",
    category: "Kerala Specials",
  },
  {
    id: 35,
    name: "Appam & Beef Fry",
    type: "Kerala Specials",
    image: "https://i.redd.it/yz7v00jq1yo51.jpg",
    price: 15.0,
    rating: 4.7,
    reviewCount: 198,
    description: "Traditional appam served with spicy Kerala beef fry.",
    category: "Kerala Specials",
  },
  {
    id: 36,
    name: "Appam & Duck Roast",
    type: "Kerala Specials",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/05/Topdown_shot_of_Palappam_with_duck_curry.jpg",
    price: 14.0,
    rating: 4.6,
    reviewCount: 167,
    description: "Soft appam paired with aromatic duck roast.",
    category: "Kerala Specials",
  },
  {
    id: 37,
    name: "Porotta & Chicken Roast",
    type: "Kerala Specials",
    image:
      "https://i.ytimg.com/vi/ypEWQZBq-yo/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAABmrdEyeyA48xljx8Tm2Kz2hZyQ",
    price: 12.0,
    rating: 4.7,
    reviewCount: 223,
    description: "Flaky layered bread served with spicy chicken roast.",
    category: "Kerala Specials",
  },
  {
    id: 38,
    name: "Porotta & Beef Roast/Fry",
    type: "Kerala Specials",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkea2QZiAofHX0_0yAKQb7dzspAv-VzybOrg&s",
    price: 15.0,
    rating: 4.8,
    reviewCount: 278,
    description: "Crispy porotta with choice of beef roast or beef fry.",
    category: "Kerala Specials",
  },
  {
    id: 39,
    name: "Porotta & Channa Dal",
    type: "Kerala Specials",
    image:
      "https://images.picxy.com/cache/2021/4/7/ce65006e269397c79b8e53feef105315.jpg",
    price: 10.0,
    rating: 4.4,
    reviewCount: 134,
    description: "Soft porotta served with spiced chickpea curry.",
    category: "Kerala Specials",
  },
  {
    id: 40,
    name: "Chola Battura",
    type: "Kerala Specials",
    image:
      "https://i.ytimg.com/vi/csfIOfMnRGg/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLB6GPMx72TdT-BQh86wkTA3VKBRpQ",
    price: 10.0,
    rating: 4.5,
    reviewCount: 156,
    description: "Spicy chickpea curry served with deep-fried bread.",
    category: "Kerala Specials",
  },
  {
    id: 41,
    name: "Kappa Fish Curry",
    type: "Kerala Specials",
    image:
      "https://lh3.ggpht.com/_OGMa3JuKVTk/TZ4dyUgrEtI/AAAAAAAAF-M/Ce65ZDpiPWU/DSC_1402_thumb%5B8%5D.jpg?imgmax=800",
    price: 10.0,
    rating: 4.6,
    reviewCount: 145,
    description: "Boiled tapioca served with traditional fish curry.",
    category: "Kerala Specials",
  },
  {
    id: 42,
    name: "Kappa Potty",
    type: "Kerala Specials",
    image:
      "https://b.zmtcdn.com/data/dish_photos/fdd/17027f9177f52f9bd8db399f8e7e0fdd.png",
    price: 14.0,
    rating: 4.3,
    reviewCount: 98,
    description: "Mashed tapioca with coconut and spices.",
    category: "Kerala Specials",
  },
  {
    id: 43,
    name: "Kappa Beef Roast/Fry",
    type: "Kerala Specials",
    image: "https://i.ytimg.com/vi/Bv0Vl3cr11g/hqdefault.jpg",
    price: 14.0,
    rating: 4.7,
    reviewCount: 189,
    description: "Tapioca served with choice of beef roast or beef fry.",
    category: "Kerala Specials",
  },
  {
    id: 44,
    name: "Masala Dosa",
    type: "South Varieties (Dosa)",
    image:
      "https://www.mydelicious-recipes.com/home/images/120_1080_1080/mydelicious-recipes-masala-dosa-with-batter",
    price: 10.0,
    rating: 4.6,
    reviewCount: 234,
    description: "Crispy rice crepe filled with spiced potato masala.",
    category: "South Varieties (Dosa)",
  },
  {
    id: 45,
    name: "Ghee Roast",
    type: "South Varieties (Dosa)",
    image:
      "https://www.qasralbaharshj.com/wp-content/uploads/2024/11/GheeRoast_1-600x600.webp",
    price: 10.0,
    rating: 4.5,
    reviewCount: 178,
    description: "Crispy dosa roasted in pure ghee with special spices.",
    category: "South Varieties (Dosa)",
  },
  {
    id: 46,
    name: "Paneer Masala Dosa",
    type: "South Varieties (Dosa)",
    image:
      "https://www.carveyourcraving.com/wp-content/uploads/2018/08/paneer-masala-for-dosa-recipe-blog.jpg",
    price: 14.0,
    rating: 4.4,
    reviewCount: 123,
    description: "Crispy dosa filled with spiced paneer and potato masala.",
    category: "South Varieties (Dosa)",
  },
  {
    id: 47,
    name: "Mysore Masala Dosa",
    type: "South Varieties (Dosa)",
    image:
      "https://i.pinimg.com/736x/2a/c1/51/2ac15169850a766390adcba3a6d28eef.jpg",
    price: 14.0,
    rating: 4.6,
    reviewCount: 167,
    description: "Spicy Mysore-style dosa with red chutney and potato filling.",
    category: "South Varieties (Dosa)",
  },
  {
    id: 48,
    name: "Egg Dosa",
    type: "South Varieties (Dosa)",
    image:
      "https://thumbs.dreamstime.com/b/delicious-masala-dosa-sides-vibrant-generated-ai-south-indian-crepe-filled-spiced-potatoes-vegetables-served-383817116.jpg",
    price: 12.0,
    rating: 4.5,
    reviewCount: 145,
    description: "Crispy dosa topped with beaten egg and spices.",
    category: "South Varieties (Dosa)",
  },
  {
    id: 49,
    name: "Thattu Dosa",
    type: "South Varieties (Dosa)",
    image: "https://i.ytimg.com/vi/t0vCNQvZBDE/sddefault.jpg",
    price: 8.0,
    rating: 4.3,
    reviewCount: 112,
    description: "Small thick dosas served as a set with chutneys.",
    category: "South Varieties (Dosa)",
  },
  {
    id: 50,
    name: "Onion Uthappam",
    type: "South Varieties (Dosa)",
    image:
      "https://revi.b-cdn.net/wp-content/uploads/2015/05/onion-uttapam-vert.jpg",
    price: 10.0,
    rating: 4.4,
    reviewCount: 134,
    description: "Thick pancake topped with onions and spices.",
    category: "South Varieties (Dosa)",
  },
  {
    id: 51,
    name: "Cheese Uthappam",
    type: "South Varieties (Dosa)",
    image:
      "https://thanjaigroup.com/thanjairestaurant/wp-content/uploads/2021/08/Uthappam-Article-2.jpg",
    price: 14.0,
    rating: 4.2,
    reviewCount: 89,
    description: "Thick pancake topped with cheese and vegetables.",
    category: "South Varieties (Dosa)",
  },
  {
    id: 52,
    name: "Idli Sambar",
    type: "South Varieties (Dosa)",
    image:
      "https://sapanarestaurant.com/wp-content/uploads/2019/11/idli-sambar-900x600.jpg",
    price: 7.0,
    rating: 4.5,
    reviewCount: 198,
    description: "Steamed rice cakes served with lentil curry.",
    category: "South Varieties (Dosa)",
  },
  {
    id: 53,
    name: "Vada Sambar",
    type: "South Varieties (Dosa)",
    image:
      "https://vegecravings.com/wp-content/uploads/2018/02/Medu-Vada-Recipe-Step-By-Step-Instructions.jpg",
    price: 7.0,
    rating: 4.4,
    reviewCount: 167,
    description: "Crispy lentil donuts served with spiced lentil curry.",
    category: "South Varieties (Dosa)",
  },
  {
    id: 54,
    name: "Tea",
    type: "Drinks",
    image:
      "https://www.munatycooking.com/wp-content/uploads/2024/04/Three-glasses-filled-with-karak-chai.jpg",
    price: 2.5,
    rating: 4.2,
    reviewCount: 245,
    description: "Traditional Indian tea brewed with milk and sugar.",
    category: "Drinks",
  },
  {
    id: 55,
    name: "Masala Tea",
    type: "Drinks",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNz8svxz897FnF-0oqyIHQwbB8VUS0-doVIQ&s",
    price: 3.5,
    rating: 4.5,
    reviewCount: 312,
    description: "Spiced tea with cardamom, ginger, and aromatic spices.",
    category: "Drinks",
  },
  {
    id: 56,
    name: "Cardamom Tea",
    type: "Drinks",
    image:
      "https://cdn.shopify.com/s/files/1/0573/8502/5710/articles/a-spicy-cup-of-goodness-how-cardamom-in-tea-boosts-your-well-being-226252.jpg?v=1736821845",
    price: 3.5,
    rating: 4.3,
    reviewCount: 189,
    description: "Fragrant tea infused with cardamom pods.",
    category: "Drinks",
  },
  {
    id: 57,
    name: "Bru Coffee",
    type: "Drinks",
    image:
      "https://cdn.shopify.com/s/files/1/0918/3414/files/perfect-cup-black-coffee.jpg?v=1498751612",
    price: 3.5,
    rating: 4.1,
    reviewCount: 156,
    description: "Strong black coffee served hot.",
    category: "Drinks",
  },
  {
    id: 58,
    name: "Mango Lassi",
    type: "Drinks",
    image:
      "https://aroundtheyum.com/wp-content/uploads/2024/09/mango-lassi-recipe.jpg",
    price: 4.0,
    rating: 4.6,
    reviewCount: 201,
    description: "Creamy yogurt drink blended with fresh mango.",
    category: "Drinks",
  },
  {
    id: 59,
    name: "Fresh Lime",
    type: "Drinks",
    image:
      "https://cdn.healthyrecipes101.com/recipes/images/juices/fresh-lime-juice-recipe-clannw7eo00kfpw1b79na4lsu.webp?w=1080&q=80",
    price: 4.0,
    rating: 4.3,
    reviewCount: 123,
    description: "Fresh lime juice with sugar and mint.",
    category: "Drinks",
  },
  {
    id: 60,
    name: "Sharjah Shake",
    type: "Drinks",
    image:
      "https://thephotowali.wordpress.com/wp-content/uploads/2018/04/fb_img_1523868519864-011008790977.jpeg",
    price: 5.0,
    rating: 4.4,
    reviewCount: 145,
    description: "Rich milkshake with nuts and dry fruits.",
    category: "Drinks",
  },
  {
    id: 61,
    name: "Vanilla Shake",
    type: "Drinks",
    image:
      "https://www.allrecipes.com/thmb/uzxCGTc-5WCUZnZ7BUcYcmWKxjo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AR-48974-vanilla-milkshake-hero-4x3-c815295c714f41f6b17b104e7403a53b.jpg",
    price: 5.0,
    rating: 4.2,
    reviewCount: 98,
    description: "Creamy vanilla milkshake with ice cream.",
    category: "Drinks",
  },
  {
    id: 62,
    name: "Fizzy Drinks",
    type: "Drinks",
    image: "https://i.redd.it/yyr6vtruhzbb1.jpg",
    price: 2.5,
    rating: 3.8,
    reviewCount: 67,
    description: "Assorted carbonated soft drinks.",
    category: "Drinks",
  },
  {
    id: 63,
    name: "Water",
    type: "Drinks",
    image:
      "https://www.seriouseats.com/thmb/CfZJlOxychcWqMRUIBGIhy3CtfU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20240401-SEA-TasteTests-AmandaSuarez-00-e7b924fdd6f4410596841e9531377ee6.jpg",
    price: 2.0,
    rating: 4.0,
    reviewCount: 45,
    description: "Pure drinking water.",
    category: "Drinks",
  },
  {
    id: 64,
    name: "Payasam",
    type: "Dessert",
    image:
      "https://vismaifood.com/storage/app/uploads/public/44e/993/010/thumb__700_0_0_0_auto.jpg",
    price: 2.0,
    rating: 4.7,
    reviewCount: 178,
    description:
      "Traditional Kerala rice pudding with coconut milk and jaggery.",
    category: "Dessert",
  },
  {
    id: 65,
    name: "Mango Pudding",
    type: "Dessert",
    image:
      "https://takestwoeggs.com/wp-content/uploads/2022/06/Mango-Pudding-Takestwoeggs-Final-Photography-sq.jpg",
    price: 2.0,
    rating: 4.4,
    reviewCount: 112,
    description: "Creamy mango pudding with fresh mango flavor.",
    category: "Dessert",
  },
  {
    id: 66,
    name: "Ladu",
    type: "Dessert",
    image: "https://static.toiimg.com/thumb/55048059.cms?width=1200&height=900",
    price: 2.0,
    rating: 4.5,
    reviewCount: 134,
    description: "Sweet round balls made with flour, ghee, and sugar.",
    category: "Dessert",
  },
  {
    id: 67,
    name: "Chocolate Cake",
    type: "Dessert",
    image:
      "https://www.indianhealthyrecipes.com/wp-content/uploads/2024/06/classic-chocolate-cake-recipe.jpg",
    price: 2.0,
    rating: 4.6,
    reviewCount: 189,
    description: "Rich chocolate cake with creamy frosting.",
    category: "Dessert",
  },
];

module.exports = { menuData };
