export const menuData = [
  {
    id: 1,
    name: "Puttu and Kadala Curry",
    type: "Breakfast",
    image:
      "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400&h=300&fit=crop&crop=center",
    price: 120,
    originalPrice: 140,
    rating: 4.5,
    reviewCount: 234,
    description:
      "Traditional Kerala breakfast with steamed rice cake and spicy black chickpea curry",
    ingredients: ["Rice flour", "Coconut", "Black chickpeas", "Spices"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "15-20 mins",
    calories: 280,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Gujarati",
    tags: ["Flatbread", "Fenugreek", "Travel food"],
    allergens: ["Gluten", "Dairy"],
    portion: "3 pieces",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "6g",
      carbs: "38g",
      fat: "8g",
      fiber: "4g",
    },
  },
  {
    id: 47,
    name: "Fafda Jalebi",
    type: "Snack",
    image:
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop&crop=center",
    price: 100,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 178,
    description: "Crispy gram flour strips with sweet spiral jalebi",
    ingredients: ["Gram flour", "Sugar", "Saffron", "Cardamom", "Oil"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "None",
    preparationTime: "30-35 mins",
    calories: 380,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "Gujarati",
    tags: ["Sweet and savory", "Traditional", "Crispy"],
    allergens: ["None"],
    portion: "2 fafda + 2 jalebi",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "8g",
      carbs: "58g",
      fat: "15g",
      fiber: "3g",
    },
  },
  {
    id: 48,
    name: "Samosa",
    type: "Snack",
    image:
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop&crop=center",
    price: 40,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 345,
    description:
      "Crispy triangular pastry filled with spiced potatoes and peas",
    ingredients: ["Flour", "Potatoes", "Peas", "Cumin", "Coriander"],
    dietary: ["Vegetarian", "Vegan"],
    spiceLevel: "Medium",
    preparationTime: "25-30 mins",
    calories: 200,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "Street Food",
    tags: ["Crispy", "Fried", "Popular"],
    allergens: ["Gluten"],
    portion: "2 pieces",
    chef: "Chef Rajesh",
    nutritionalInfo: {
      protein: "4g",
      carbs: "28g",
      fat: "12g",
      fiber: "3g",
    },
  },
  {
    id: 49,
    name: "Pakora",
    type: "Snack",
    image:
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop&crop=center",
    price: 80,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 198,
    description: "Mixed vegetable fritters in spiced gram flour batter",
    ingredients: [
      "Mixed vegetables",
      "Gram flour",
      "Spices",
      "Ginger",
      "Green chilies",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "20-25 mins",
    calories: 220,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "Street Food",
    tags: ["Fried", "Monsoon special", "Tea-time"],
    allergens: ["None"],
    portion: "6 pieces",
    chef: "Chef Rajesh",
    nutritionalInfo: {
      protein: "6g",
      carbs: "24g",
      fat: "12g",
      fiber: "4g",
    },
  },
  {
    id: 50,
    name: "Naan",
    type: "Bread",
    image:
      "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop&crop=center",
    price: 50,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 267,
    description: "Soft leavened bread baked in tandoor",
    ingredients: ["Flour", "Yogurt", "Yeast", "Ghee", "Salt"],
    dietary: ["Vegetarian"],
    spiceLevel: "None",
    preparationTime: "15-20 mins",
    calories: 280,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "North Indian",
    tags: ["Tandoor", "Soft", "Leavened"],
    allergens: ["Gluten", "Dairy"],
    portion: "1 piece",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "8g",
      carbs: "52g",
      fat: "6g",
      fiber: "2g",
    },
  },
  {
    id: 51,
    name: "Poori",
    type: "Bread",
    image:
      "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop&crop=center",
    price: 60,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 156,
    description: "Deep-fried puffed bread, crispy and golden",
    ingredients: ["Wheat flour", "Oil", "Salt", "Water"],
    dietary: ["Vegetarian", "Vegan"],
    spiceLevel: "None",
    preparationTime: "15-20 mins",
    calories: 180,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "North Indian",
    tags: ["Fried", "Puffed", "Crispy"],
    allergens: ["Gluten"],
    portion: "3 pieces",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "5g",
      carbs: "32g",
      fat: "8g",
      fiber: "2g",
    },
  },
  {
    id: 52,
    name: "Jeera Rice",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop&crop=center",
    price: 140,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 178,
    description: "Fragrant basmati rice cooked with cumin seeds",
    ingredients: [
      "Basmati rice",
      "Cumin seeds",
      "Ghee",
      "Bay leaves",
      "Onions",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "20-25 mins",
    calories: 320,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "North Indian",
    tags: ["Aromatic", "Simple", "Cumin"],
    allergens: ["Dairy"],
    portion: "1 serving",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "6g",
      carbs: "65g",
      fat: "6g",
      fiber: "2g",
    },
  },
  {
    id: 53,
    name: "Plain Dosa",
    type: "Breakfast",
    image:
      "https://images.unsplash.com/photo-1630383249896-424e482df921?w=400&h=300&fit=crop&crop=center",
    price: 100,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 234,
    description: "Crispy golden rice crepe served with chutney and sambar",
    ingredients: ["Rice", "Urad dal", "Salt"],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "None",
    preparationTime: "10-15 mins",
    calories: 180,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "South Indian",
    tags: ["Plain", "Crispy", "Classic"],
    allergens: ["None"],
    portion: "1 dosa",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "6g",
      carbs: "35g",
      fat: "2g",
      fiber: "2g",
    },
  },
  {
    id: 54,
    name: "Vegetable Biryani",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1563379091339-03246963d96c?w=400&h=300&fit=crop&crop=center",
    price: 280,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 198,
    description:
      "Fragrant basmati rice layered with spiced vegetables and saffron",
    ingredients: [
      "Basmati rice",
      "Mixed vegetables",
      "Saffron",
      "Yogurt",
      "Biryani masala",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "45-50 mins",
    calories: 420,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "North Indian",
    tags: ["Layered", "Fragrant", "Festive"],
    allergens: ["Dairy"],
    portion: "1 full portion",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "12g",
      carbs: "78g",
      fat: "12g",
      fiber: "6g",
    },
  },
  {
    id: 55,
    name: "Gulab Jamun",
    type: "Dessert",
    image:
      "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop&crop=center",
    price: 70,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 345,
    description: "Soft milk dumplings soaked in rose-flavored sugar syrup",
    ingredients: ["Milk powder", "Sugar", "Rose water", "Cardamom", "Ghee"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "None",
    preparationTime: "25-30 mins",
    calories: 250,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "North Indian",
    tags: ["Sweet", "Soft", "Popular"],
    allergens: ["Dairy"],
    portion: "2 pieces",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "6g",
      carbs: "38g",
      fat: "12g",
      fiber: "0g",
    },
  },
  {
    id: 56,
    name: "Rasmalai",
    type: "Dessert",
    image:
      "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop&crop=center",
    price: 90,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 234,
    description: "Soft cottage cheese dumplings in sweetened condensed milk",
    ingredients: ["Cottage cheese", "Milk", "Sugar", "Cardamom", "Pistachios"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "None",
    preparationTime: "40-45 mins",
    calories: 280,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Bengali",
    tags: ["Creamy", "Delicate", "Premium"],
    allergens: ["Dairy", "Nuts"],
    portion: "2 pieces",
    chef: "Chef Sujata",
    nutritionalInfo: {
      protein: "12g",
      carbs: "32g",
      fat: "14g",
      fiber: "0g",
    },
  },
  {
    id: 57,
    name: "Sandesh",
    type: "Dessert",
    image:
      "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop&crop=center",
    price: 60,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 145,
    description: "Bengali cottage cheese sweet, delicate and mildly flavored",
    ingredients: ["Fresh cottage cheese", "Sugar", "Cardamom", "Rose essence"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "None",
    preparationTime: "20-25 mins",
    calories: 180,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Bengali",
    tags: ["Light", "Delicate", "Traditional"],
    allergens: ["Dairy"],
    portion: "2 pieces",
    chef: "Chef Sujata",
    nutritionalInfo: {
      protein: "8g",
      carbs: "24g",
      fat: "6g",
      fiber: "0g",
    },
  },
  {
    id: 58,
    name: "Pakhala Bhata",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop&crop=center",
    price: 120,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 89,
    description: "Fermented rice with water, a cooling Odia summer dish",
    ingredients: ["Rice", "Water", "Salt", "Curd", "Ginger"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "None",
    preparationTime: "12 hours + 10 mins",
    calories: 220,
    isAvailable: false,
    isRecommended: false,
    isPopular: false,
    category: "Odia",
    tags: ["Fermented", "Cooling", "Summer special"],
    allergens: ["Dairy"],
    portion: "1 serving",
    chef: "Chef Pradeep",
    nutritionalInfo: {
      protein: "5g",
      carbs: "45g",
      fat: "2g",
      fiber: "2g",
    },
  },
  {
    id: 59,
    name: "Chhena Poda",
    type: "Dessert",
    image:
      "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop&crop=center",
    price: 80,
    originalPrice: null,
    rating: 4.5,
    reviewCount: 123,
    description:
      "Baked cottage cheese dessert with caramelized sugar - Odia specialty",
    ingredients: ["Fresh cottage cheese", "Sugar", "Cardamom", "Cashews"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "None",
    preparationTime: "60-70 mins",
    calories: 320,
    isAvailable: true,
    isRecommended: true,
    isPopular: false,
    category: "Odia",
    tags: ["Baked", "Caramelized", "Unique"],
    allergens: ["Dairy", "Nuts"],
    portion: "1 slice",
    chef: "Chef Pradeep",
    nutritionalInfo: {
      protein: "14g",
      carbs: "42g",
      fat: "12g",
      fiber: "1g",
    },
  },
  {
    id: 60,
    name: "Dalma",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop&crop=center",
    price: 160,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 78,
    description:
      "Lentils cooked with vegetables and mild spices - Odia comfort food",
    ingredients: [
      "Arhar dal",
      "Mixed vegetables",
      "Turmeric",
      "Cumin",
      "Curry leaves",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "30-35 mins",
    calories: 240,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Odia",
    tags: ["Comfort food", "Nutritious", "Traditional"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Pradeep",
    nutritionalInfo: {
      protein: "16g",
      carbs: "35g",
      fat: "4g",
      fiber: "12g",
    },
  },
  {
    id: 61,
    name: "Santula",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop&crop=center",
    price: 140,
    originalPrice: null,
    rating: 4.0,
    reviewCount: 56,
    description:
      "Mixed vegetable curry without onion and garlic - Odia temple food",
    ingredients: [
      "Mixed vegetables",
      "Ginger",
      "Cumin",
      "Turmeric",
      "Mustard oil",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "25-30 mins",
    calories: 180,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Odia",
    tags: ["Temple food", "No onion-garlic", "Pure"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Pradeep",
    nutritionalInfo: {
      protein: "6g",
      carbs: "32g",
      fat: "5g",
      fiber: "8g",
    },
  },
  {
    id: 62,
    name: "Khechudi",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop&crop=center",
    price: 130,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 67,
    description:
      "Odia comfort food - rice and lentils cooked together with mild spices",
    ingredients: ["Rice", "Moong dal", "Ghee", "Cumin", "Hing"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "25-30 mins",
    calories: 290,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Odia",
    tags: ["Comfort food", "One-pot", "Simple"],
    allergens: ["Dairy"],
    portion: "1 serving",
    chef: "Chef Pradeep",
    nutritionalInfo: {
      protein: "12g",
      carbs: "52g",
      fat: "6g",
      fiber: "4g",
    },
  },
  {
    id: 63,
    name: "Pesarattu",
    type: "Breakfast",
    image:
      "https://images.unsplash.com/photo-1630383249896-424e482df921?w=400&h=300&fit=crop&crop=center",
    price: 120,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 145,
    description:
      "Green gram crepe from Andhra Pradesh, nutritious and protein-rich",
    ingredients: [
      "Green gram",
      "Rice",
      "Ginger",
      "Green chilies",
      "Curry leaves",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "20-25 mins",
    calories: 220,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Telugu",
    tags: ["Protein-rich", "Healthy", "Green gram"],
    allergens: ["None"],
    portion: "1 pesarattu",
    chef: "Chef Lakshmi",
    nutritionalInfo: {
      protein: "12g",
      carbs: "35g",
      fat: "4g",
      fiber: "6g",
    },
  },
  {
    id: 64,
    name: "Gongura Pachadi",
    type: "Side Dish",
    image:
      "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop&crop=center",
    price: 90,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 98,
    description: "Tangy sorrel leaves chutney - signature Andhra dish",
    ingredients: [
      "Gongura leaves",
      "Red chilies",
      "Garlic",
      "Tamarind",
      "Sesame oil",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Hot",
    preparationTime: "15-20 mins",
    calories: 80,
    isAvailable: true,
    isRecommended: true,
    isPopular: false,
    category: "Telugu",
    tags: ["Tangy", "Signature dish", "Spicy"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Lakshmi",
    nutritionalInfo: {
      protein: "2g",
      carbs: "8g",
      fat: "6g",
      fiber: "4g",
    },
  },
  {
    id: 65,
    name: "Pulihora",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop&crop=center",
    price: 140,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 123,
    description: "Tangy tamarind rice with peanuts and spices",
    ingredients: [
      "Rice",
      "Tamarind",
      "Peanuts",
      "Mustard seeds",
      "Curry leaves",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "20-25 mins",
    calories: 320,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "Telugu",
    tags: ["Tangy", "Festival food", "Travel friendly"],
    allergens: ["Nuts"],
    portion: "1 serving",
    chef: "Chef Lakshmi",
    nutritionalInfo: {
      protein: "8g",
      carbs: "58g",
      fat: "8g",
      fiber: "4g",
    },
  },
  {
    id: 66,
    name: "Kodi Kura",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&h=300&fit=crop&crop=center",
    price: 320,
    originalPrice: null,
    rating: 4.5,
    reviewCount: 167,
    description: "Spicy Andhra chicken curry with aromatic spices",
    ingredients: ["Chicken", "Onions", "Red chilies", "Coriander", "Coconut"],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Hot",
    preparationTime: "35-40 mins",
    calories: 380,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "Telugu",
    tags: ["Spicy", "Aromatic", "Traditional"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Lakshmi",
    nutritionalInfo: {
      protein: "32g",
      carbs: "12g",
      fat: "18g",
      fiber: "3g",
    },
  },
  {
    id: 67,
    name: "Bobbatlu",
    type: "Dessert",
    image:
      "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop&crop=center",
    price: 80,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 189,
    description: "Sweet stuffed flatbread with jaggery and lentil filling",
    ingredients: ["Flour", "Chana dal", "Jaggery", "Cardamom", "Ghee"],
    dietary: ["Vegetarian"],
    spiceLevel: "None",
    preparationTime: "40-45 mins",
    calories: 320,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Telugu",
    tags: ["Sweet", "Festive", "Traditional"],
    allergens: ["Gluten", "Dairy"],
    portion: "2 pieces",
    chef: "Chef Lakshmi",
    nutritionalInfo: {
      protein: "8g",
      carbs: "58g",
      fat: "8g",
      fiber: "4g",
    },
  },
  {
    id: 68,
    name: "Vindaloo",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&h=300&fit=crop&crop=center",
    price: 380,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 234,
    description: "Spicy Goan curry with pork/chicken in vinegar-based sauce",
    ingredients: ["Pork/Chicken", "Vinegar", "Red chilies", "Garlic", "Ginger"],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Very Hot",
    preparationTime: "45-50 mins",
    calories: 420,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Goan",
    tags: ["Spicy", "Vinegar-based", "Portuguese influence"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Carlos",
    nutritionalInfo: {
      protein: "35g",
      carbs: "8g",
      fat: "22g",
      fiber: "2g",
    },
  },
  {
    id: 69,
    name: "Xacuti",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&h=300&fit=crop&crop=center",
    price: 350,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 145,
    description: "Complex Goan curry with roasted spices and coconut",
    ingredients: ["Chicken", "Coconut", "Poppy seeds", "Red chilies", "Spices"],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "40-45 mins",
    calories: 380,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Goan",
    tags: ["Complex spices", "Coconut-based", "Traditional"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Carlos",
    description: "Coconut-based prawn curry with kokum and spices",
    isAvailable: true,
    nutritionalInfo: {
      protein: "30g",
      carbs: "15g",
      fat: "20g",
      fiber: "4g",
    },
  },
  {
    id: 70,
    name: "Bebinca",
    type: "Dessert",
    image:
      "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop&crop=center",
    price: 120,
    originalPrice: null,
    rating: 4.8,
    reviewCount: 178,
    description: "Layered Goan dessert with coconut milk and jaggery",
    ingredients: ["Coconut milk", "Jaggery", "Eggs", "Flour", "Nutmeg"],
    dietary: ["Vegetarian"],
    spiceLevel: "None",
    preparationTime: "90-120 mins",
    calories: 350,
    isAvailable: true,
    isRecommended: true,
    isPopular: false,
    category: "Goan",
    tags: ["Layered", "Rich", "Portuguese influence"],
    allergens: ["Gluten", "Dairy", "Eggs"],
    portion: "1 slice",
    chef: "Chef Carlos",
    nutritionalInfo: {
      protein: "6g",
      carbs: "58g",
      fat: "14g",
      fiber: "2g",
    },
  },
  {
    id: 71,
    name: "Goan Prawn Curry",
    type: "Seafood",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop&crop=center",
    price: 420,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 198,
    description: "Coconut-based prawn curry with kokum and spices",
    category: "Kerala Special",
    tags: ["Traditional", "Healthy", "Breakfast Special"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Radhika",
    nutritionalInfo: {
      protein: "12g",
      carbs: "45g",
      fat: "8g",
      fiber: "6g",
    },
  },
  {
    id: 2,
    name: "Appam with Stew",
    type: "Breakfast",
    image:
      "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop&crop=center",
    price: 150,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 189,
    description:
      "Soft fermented rice pancakes served with aromatic coconut milk stew",
    ingredients: ["Rice", "Coconut milk", "Mixed vegetables", "Spices"],
    dietary: ["Vegetarian", "Dairy-free"],
    spiceLevel: "Mild",
    preparationTime: "20-25 mins",
    calories: 320,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala Special",
    tags: ["Traditional", "Coconut", "Fermented"],
    allergens: ["None"],
    portion: "2 appams with stew",
    chef: "Chef Radhika",
    nutritionalInfo: {
      protein: "8g",
      carbs: "52g",
      fat: "12g",
      fiber: "4g",
    },
  },
  {
    id: 3,
    name: "Karimeen Pollichathu",
    type: "Seafood",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop&crop=center",
    price: 450,
    originalPrice: null,
    rating: 4.8,
    reviewCount: 156,
    description:
      "Pearl spot fish marinated in spices, wrapped in banana leaf and grilled",
    ingredients: [
      "Pearl spot fish",
      "Coconut",
      "Red chili",
      "Turmeric",
      "Banana leaf",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "30-35 mins",
    calories: 380,
    isAvailable: true,
    isRecommended: true,
    isPopular: false,
    category: "Kerala Special",
    tags: ["Grilled", "Banana leaf", "Signature dish"],
    allergens: ["Fish"],
    portion: "1 whole fish",
    chef: "Chef Mohanan",
    nutritionalInfo: {
      protein: "35g",
      carbs: "8g",
      fat: "15g",
      fiber: "2g",
    },
  },
  {
    id: 4,
    name: "Erissery",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop&crop=center",
    price: 180,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 98,
    description:
      "Traditional Kerala curry with pumpkin, yam and coconut cooked with black-eyed peas",
    ingredients: ["Pumpkin", "Yam", "Black-eyed peas", "Coconut", "Spices"],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "25-30 mins",
    calories: 220,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Kerala Special",
    tags: ["Traditional", "Healthy", "Curry"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Radhika",
    nutritionalInfo: {
      protein: "8g",
      carbs: "35g",
      fat: "6g",
      fiber: "8g",
    },
  },
  {
    id: 5,
    name: "Avial",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop&crop=center",
    price: 160,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 142,
    description:
      "Mixed vegetable curry with coconut and curry leaves - a Kerala classic",
    ingredients: [
      "Mixed vegetables",
      "Coconut",
      "Curry leaves",
      "Yogurt",
      "Turmeric",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "20-25 mins",
    calories: 190,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala Special",
    tags: ["Traditional", "Mixed vegetables", "Coconut"],
    allergens: ["Dairy"],
    portion: "1 serving",
    chef: "Chef Radhika",
    nutritionalInfo: {
      protein: "6g",
      carbs: "28g",
      fat: "8g",
      fiber: "7g",
    },
  },
  {
    id: 6,
    name: "Thoran",
    type: "Side Dish",
    image:
      "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop&crop=center",
    price: 90,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 87,
    description: "Dry vegetable stir-fry with grated coconut and spices",
    ingredients: [
      "Cabbage",
      "Coconut",
      "Mustard seeds",
      "Curry leaves",
      "Green chilies",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "10-15 mins",
    calories: 110,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Kerala Special",
    tags: ["Stir-fry", "Coconut", "Side dish"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Radhika",
    nutritionalInfo: {
      protein: "3g",
      carbs: "12g",
      fat: "8g",
      fiber: "4g",
    },
  },
  {
    id: 7,
    name: "Kerala Fish Moilee",
    type: "Seafood",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop&crop=center",
    price: 380,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 201,
    description:
      "Fish curry cooked in coconut milk with mild spices - a coastal delight",
    ingredients: [
      "Fish",
      "Coconut milk",
      "Onion",
      "Ginger",
      "Turmeric",
      "Curry leaves",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "25-30 mins",
    calories: 320,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala Special",
    tags: ["Coconut curry", "Mild", "Fish"],
    allergens: ["Fish"],
    portion: "1 serving with rice",
    chef: "Chef Mohanan",
    nutritionalInfo: {
      protein: "28g",
      carbs: "12g",
      fat: "18g",
      fiber: "2g",
    },
  },
  {
    id: 8,
    name: "Kerala Beef Fry",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&h=300&fit=crop&crop=center",
    price: 420,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 312,
    description:
      "Spicy dry-roasted beef with coconut slices and aromatic spices",
    ingredients: ["Beef", "Coconut slices", "Onion", "Spices", "Curry leaves"],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Hot",
    preparationTime: "45-50 mins",
    calories: 450,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala Special",
    tags: ["Spicy", "Roasted", "Signature dish"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Mohanan",
    nutritionalInfo: {
      protein: "35g",
      carbs: "8g",
      fat: "25g",
      fiber: "3g",
    },
  },
  {
    id: 9,
    name: "Idiyappam",
    type: "Breakfast",
    image:
      "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400&h=300&fit=crop&crop=center",
    price: 100,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 76,
    description: "Steamed rice noodles served with coconut milk or curry",
    ingredients: ["Rice flour", "Coconut", "Salt"],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "15-20 mins",
    calories: 240,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Kerala Special",
    tags: ["Steamed", "Rice noodles", "Light"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Radhika",
    nutritionalInfo: {
      protein: "4g",
      carbs: "48g",
      fat: "2g",
      fiber: "2g",
    },
  },
  {
    id: 10,
    name: "Palada Payasam",
    type: "Dessert",
    image:
      "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop&crop=center",
    price: 80,
    originalPrice: null,
    rating: 4.8,
    reviewCount: 167,
    description: "Traditional Kerala dessert with rice ada, milk and jaggery",
    ingredients: ["Rice ada", "Milk", "Jaggery", "Cardamom", "Cashews"],
    dietary: ["Vegetarian"],
    spiceLevel: "None",
    preparationTime: "30-35 mins",
    calories: 280,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "Kerala Special",
    tags: ["Sweet", "Traditional", "Festival special"],
    allergens: ["Dairy", "Nuts"],
    portion: "1 bowl",
    chef: "Chef Radhika",
    nutritionalInfo: {
      protein: "8g",
      carbs: "45g",
      fat: "8g",
      fiber: "1g",
    },
  },
  {
    id: 11,
    name: "Kappa and Meen Curry",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop&crop=center",
    price: 250,
    originalPrice: null,
    rating: 4.5,
    reviewCount: 143,
    description:
      "Boiled tapioca served with spicy fish curry - a coastal favorite",
    ingredients: ["Tapioca", "Fish", "Coconut", "Tamarind", "Red chilies"],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "35-40 mins",
    calories: 380,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "Kerala Special",
    tags: ["Traditional", "Coastal", "Fish curry"],
    allergens: ["Fish"],
    portion: "1 serving",
    chef: "Chef Mohanan",
    nutritionalInfo: {
      protein: "25g",
      carbs: "45g",
      fat: "12g",
      fiber: "5g",
    },
  },
  {
    id: 12,
    name: "Parippu Curry",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop&crop=center",
    price: 140,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 92,
    description:
      "Simple and comforting lentil curry with coconut and curry leaves",
    ingredients: [
      "Lentils",
      "Coconut",
      "Turmeric",
      "Curry leaves",
      "Green chilies",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "20-25 mins",
    calories: 200,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Kerala Special",
    tags: ["Lentils", "Comfort food", "Healthy"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Radhika",
    nutritionalInfo: {
      protein: "14g",
      carbs: "28g",
      fat: "4g",
      fiber: "8g",
    },
  },
  {
    id: 13,
    name: "Sambar",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop&crop=center",
    price: 120,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 234,
    description:
      "Traditional South Indian lentil soup with vegetables and tamarind",
    ingredients: [
      "Toor dal",
      "Mixed vegetables",
      "Tamarind",
      "Sambar powder",
      "Curry leaves",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "25-30 mins",
    calories: 180,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "South Indian",
    tags: ["Lentil soup", "Traditional", "Healthy"],
    allergens: ["None"],
    portion: "1 bowl",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "12g",
      carbs: "25g",
      fat: "3g",
      fiber: "9g",
    },
  },
  {
    id: 14,
    name: "Rasam",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop&crop=center",
    price: 100,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 156,
    description: "Tangy and spicy South Indian soup with tomatoes and tamarind",
    ingredients: [
      "Tomatoes",
      "Tamarind",
      "Toor dal",
      "Rasam powder",
      "Coriander",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "15-20 mins",
    calories: 85,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "South Indian",
    tags: ["Soup", "Tangy", "Light"],
    allergens: ["None"],
    portion: "1 bowl",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "3g",
      carbs: "15g",
      fat: "2g",
      fiber: "3g",
    },
  },
  {
    id: 15,
    name: "Curd Rice",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop&crop=center",
    price: 90,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 187,
    description: "Comforting rice mixed with yogurt and tempered with spices",
    ingredients: ["Rice", "Yogurt", "Mustard seeds", "Curry leaves", "Ginger"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "10-15 mins",
    calories: 260,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "South Indian",
    tags: ["Comfort food", "Cooling", "Simple"],
    allergens: ["Dairy"],
    portion: "1 serving",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "8g",
      carbs: "48g",
      fat: "4g",
      fiber: "2g",
    },
  },
  {
    id: 16,
    name: "Lemon Rice",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop&crop=center",
    price: 110,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 134,
    description: "Tangy rice dish with lemon juice, turmeric and nuts",
    ingredients: ["Rice", "Lemon", "Turmeric", "Peanuts", "Curry leaves"],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "15-20 mins",
    calories: 290,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "South Indian",
    tags: ["Tangy", "Rice dish", "Nuts"],
    allergens: ["Nuts"],
    portion: "1 serving",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "7g",
      carbs: "52g",
      fat: "8g",
      fiber: "3g",
    },
  },
  {
    id: 17,
    name: "Coconut Rice",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop&crop=center",
    price: 120,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 98,
    description: "Aromatic rice cooked with fresh coconut and spices",
    ingredients: [
      "Rice",
      "Fresh coconut",
      "Cashews",
      "Raisins",
      "Curry leaves",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "20-25 mins",
    calories: 320,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "South Indian",
    tags: ["Coconut", "Aromatic", "Festive"],
    allergens: ["Nuts"],
    portion: "1 serving",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "6g",
      carbs: "55g",
      fat: "12g",
      fiber: "4g",
    },
  },
  {
    id: 18,
    name: "Tamarind Rice",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop&crop=center",
    price: 130,
    originalPrice: null,
    rating: 4.0,
    reviewCount: 112,
    description: "Tangy rice dish with tamarind pulp and South Indian spices",
    ingredients: ["Rice", "Tamarind", "Peanuts", "Sesame oil", "Red chilies"],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "20-25 mins",
    calories: 310,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "South Indian",
    tags: ["Tangy", "Traditional", "Spiced rice"],
    allergens: ["Nuts"],
    portion: "1 serving",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "8g",
      carbs: "58g",
      fat: "7g",
      fiber: "4g",
    },
  },
  {
    id: 19,
    name: "Bisi Bele Bath",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop&crop=center",
    price: 160,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 178,
    description:
      "Karnataka's famous one-pot meal with rice, lentils and vegetables",
    ingredients: [
      "Rice",
      "Toor dal",
      "Mixed vegetables",
      "Tamarind",
      "Bisi bele bath powder",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "30-35 mins",
    calories: 350,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "South Indian",
    tags: ["One-pot", "Karnataka special", "Complete meal"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "15g",
      carbs: "62g",
      fat: "6g",
      fiber: "8g",
    },
  },
  {
    id: 20,
    name: "Chena Mezhukkupuratti",
    type: "Side Dish",
    image:
      "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop&crop=center",
    price: 70,
    originalPrice: null,
    rating: 4.0,
    reviewCount: 54,
    description: "Stir-fried yam with coconut and spices - a Kerala delicacy",
    ingredients: [
      "Yam",
      "Coconut",
      "Shallots",
      "Green chilies",
      "Curry leaves",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "15-20 mins",
    calories: 140,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Kerala Special",
    tags: ["Stir-fry", "Yam", "Traditional"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Radhika",
    nutritionalInfo: {
      protein: "2g",
      carbs: "28g",
      fat: "4g",
      fiber: "5g",
    },
  },
  {
    id: 21,
    name: "Hyderabadi Biryani",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1563379091339-03246963d96c?w=400&h=300&fit=crop&crop=center",
    price: 380,
    originalPrice: 420,
    rating: 4.7,
    reviewCount: 456,
    description:
      "Authentic Hyderabadi dum biryani with tender meat and aromatic basmati rice",
    ingredients: [
      "Basmati rice",
      "Mutton/Chicken",
      "Saffron",
      "Yogurt",
      "Biryani masala",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "60-70 mins",
    calories: 520,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "North Indian",
    tags: ["Biryani", "Dum cooking", "Signature dish"],
    allergens: ["Dairy"],
    portion: "1 full portion",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "32g",
      carbs: "68g",
      fat: "16g",
      fiber: "3g",
    },
  },
  {
    id: 22,
    name: "Butter Chicken",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&h=300&fit=crop&crop=center",
    price: 320,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 389,
    description:
      "Creamy tomato-based curry with tender chicken pieces in rich butter gravy",
    ingredients: ["Chicken", "Tomatoes", "Butter", "Cream", "Garam masala"],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "35-40 mins",
    calories: 420,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "North Indian",
    tags: ["Creamy", "Popular", "Mild spice"],
    allergens: ["Dairy"],
    portion: "1 serving with rice/naan",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "28g",
      carbs: "15g",
      fat: "26g",
      fiber: "3g",
    },
  },
  {
    id: 23,
    name: "Paneer Butter Masala",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop&crop=center",
    price: 280,
    originalPrice: null,
    rating: 4.5,
    reviewCount: 267,
    description: "Soft paneer cubes in rich tomato and butter gravy",
    ingredients: ["Paneer", "Tomatoes", "Butter", "Cream", "Cashews"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "25-30 mins",
    calories: 380,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "North Indian",
    tags: ["Paneer", "Creamy", "Popular"],
    allergens: ["Dairy", "Nuts"],
    portion: "1 serving",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "18g",
      carbs: "20g",
      fat: "22g",
      fiber: "4g",
    },
  },
  {
    id: 24,
    name: "Chole Bhature",
    type: "Breakfast",
    image:
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop&crop=center",
    price: 180,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 298,
    description: "Spicy chickpea curry served with fluffy deep-fried bread",
    ingredients: ["Chickpeas", "Flour", "Yogurt", "Spices", "Oil"],
    dietary: ["Vegetarian"],
    spiceLevel: "Medium",
    preparationTime: "30-35 mins",
    calories: 480,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "North Indian",
    tags: ["Spicy", "Fried bread", "Popular"],
    allergens: ["Gluten", "Dairy"],
    portion: "2 bhature with chole",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "16g",
      carbs: "68g",
      fat: "18g",
      fiber: "12g",
    },
  },
  {
    id: 25,
    name: "Rajma Chawal",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop&crop=center",
    price: 200,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 178,
    description: "Kidney bean curry served with steamed basmati rice",
    ingredients: [
      "Kidney beans",
      "Onions",
      "Tomatoes",
      "Spices",
      "Basmati rice",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "40-45 mins",
    calories: 380,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "North Indian",
    tags: ["Comfort food", "Protein rich", "Complete meal"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "18g",
      carbs: "65g",
      fat: "6g",
      fiber: "15g",
    },
  },
  {
    id: 26,
    name: "Dal Makhani",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop&crop=center",
    price: 250,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 234,
    description: "Creamy black lentils slow-cooked with butter and cream",
    ingredients: ["Black lentils", "Butter", "Cream", "Tomatoes", "Spices"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "60-70 mins",
    calories: 320,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "North Indian",
    tags: ["Creamy", "Rich", "Slow-cooked"],
    allergens: ["Dairy"],
    portion: "1 serving",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "20g",
      carbs: "28g",
      fat: "12g",
      fiber: "18g",
    },
  },
  {
    id: 27,
    name: "Tandoori Chicken",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&h=300&fit=crop&crop=center",
    price: 350,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 312,
    description: "Marinated chicken grilled in tandoor with aromatic spices",
    ingredients: [
      "Chicken",
      "Yogurt",
      "Tandoori masala",
      "Lemon",
      "Ginger-garlic",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "45-50 mins",
    calories: 280,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "North Indian",
    tags: ["Grilled", "Tandoor", "Healthy"],
    allergens: ["Dairy"],
    portion: "Half chicken",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "35g",
      carbs: "6g",
      fat: "12g",
      fiber: "1g",
    },
  },
  {
    id: 28,
    name: "Makki di Roti & Sarson da Saag",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop&crop=center",
    price: 220,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 145,
    description:
      "Corn flour flatbread served with mustard greens curry and butter",
    ingredients: [
      "Corn flour",
      "Mustard greens",
      "Spinach",
      "Butter",
      "Spices",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "40-45 mins",
    calories: 350,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "North Indian",
    tags: ["Traditional", "Healthy greens", "Winter special"],
    allergens: ["Dairy"],
    portion: "2 rotis with saag",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "12g",
      carbs: "48g",
      fat: "14g",
      fiber: "8g",
    },
  },
  {
    id: 29,
    name: "Lassi",
    type: "Drink",
    image:
      "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop&crop=center",
    price: 60,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 189,
    description: "Traditional yogurt-based drink, sweet or salty",
    ingredients: ["Yogurt", "Sugar/Salt", "Cardamom", "Rose water"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "None",
    preparationTime: "5-10 mins",
    calories: 150,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "North Indian",
    tags: ["Refreshing", "Traditional drink", "Cooling"],
    allergens: ["Dairy"],
    portion: "1 glass",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "6g",
      carbs: "22g",
      fat: "4g",
      fiber: "0g",
    },
  },
  {
    id: 30,
    name: "Aloo Paratha",
    type: "Breakfast",
    image:
      "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400&h=300&fit=crop&crop=center",
    price: 120,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 267,
    description:
      "Stuffed flatbread with spiced potato filling served with yogurt and pickle",
    ingredients: ["Wheat flour", "Potatoes", "Spices", "Ghee"],
    dietary: ["Vegetarian"],
    spiceLevel: "Mild",
    preparationTime: "20-25 mins",
    calories: 320,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "North Indian",
    tags: ["Stuffed bread", "Potato", "Comfort food"],
    allergens: ["Gluten", "Dairy"],
    portion: "2 parathas",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "8g",
      carbs: "56g",
      fat: "10g",
      fiber: "4g",
    },
  },
  {
    id: 31,
    name: "Masala Dosa",
    type: "Breakfast",
    image:
      "https://images.unsplash.com/photo-1630383249896-424e482df921?w=400&h=300&fit=crop&crop=center",
    price: 140,
    originalPrice: null,
    rating: 4.5,
    reviewCount: 456,
    description:
      "Crispy rice crepe filled with spiced potato curry, served with chutney and sambar",
    ingredients: ["Rice", "Urad dal", "Potatoes", "Onions", "Spices"],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "15-20 mins",
    calories: 280,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "South Indian",
    tags: ["Crispy", "Fermented", "Popular"],
    allergens: ["None"],
    portion: "1 dosa",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "8g",
      carbs: "52g",
      fat: "6g",
      fiber: "4g",
    },
  },
  {
    id: 32,
    name: "Rava Idli",
    type: "Breakfast",
    image:
      "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400&h=300&fit=crop&crop=center",
    price: 100,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 134,
    description: "Steamed semolina cakes with vegetables, light and fluffy",
    ingredients: [
      "Semolina",
      "Yogurt",
      "Mixed vegetables",
      "Spices",
      "Curry leaves",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "15-20 mins",
    calories: 220,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "South Indian",
    tags: ["Steamed", "Light", "Healthy"],
    allergens: ["Dairy"],
    portion: "3 pieces",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "6g",
      carbs: "42g",
      fat: "4g",
      fiber: "3g",
    },
  },
  {
    id: 33,
    name: "Mysore Pak",
    type: "Dessert",
    image:
      "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop&crop=center",
    price: 90,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 198,
    description:
      "Traditional Karnataka sweet made with gram flour, ghee and sugar",
    ingredients: ["Gram flour", "Ghee", "Sugar", "Cardamom"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "None",
    preparationTime: "25-30 mins",
    calories: 320,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "South Indian",
    tags: ["Sweet", "Traditional", "Festive"],
    allergens: ["Dairy"],
    portion: "2 pieces",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "6g",
      carbs: "45g",
      fat: "18g",
      fiber: "2g",
    },
  },
  {
    id: 34,
    name: "Rava Dosa",
    type: "Breakfast",
    image:
      "https://images.unsplash.com/photo-1630383249896-424e482df921?w=400&h=300&fit=crop&crop=center",
    price: 160,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 178,
    description: "Crispy semolina crepe with onions and spices",
    ingredients: [
      "Semolina",
      "Rice flour",
      "Onions",
      "Green chilies",
      "Coriander",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "15-20 mins",
    calories: 250,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "South Indian",
    tags: ["Crispy", "Instant", "No fermentation"],
    allergens: ["None"],
    portion: "1 dosa",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "6g",
      carbs: "48g",
      fat: "5g",
      fiber: "3g",
    },
  },
  {
    id: 35,
    name: "Uttapam",
    type: "Breakfast",
    image:
      "https://images.unsplash.com/photo-1630383249896-424e482df921?w=400&h=300&fit=crop&crop=center",
    price: 130,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 145,
    description: "Thick pancake topped with vegetables, served with chutney",
    ingredients: ["Rice", "Urad dal", "Onions", "Tomatoes", "Capsicum"],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "15-20 mins",
    calories: 260,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "South Indian",
    tags: ["Thick pancake", "Vegetables", "Fermented"],
    allergens: ["None"],
    portion: "1 uttapam",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "8g",
      carbs: "50g",
      fat: "4g",
      fiber: "5g",
    },
  },
  {
    id: 36,
    name: "Vada",
    type: "Snack",
    image:
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop&crop=center",
    price: 60,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 167,
    description: "Deep-fried lentil donuts, crispy outside and soft inside",
    ingredients: ["Urad dal", "Ginger", "Green chilies", "Curry leaves", "Oil"],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "20-25 mins",
    calories: 180,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "South Indian",
    tags: ["Fried", "Crispy", "Tea-time snack"],
    allergens: ["None"],
    portion: "2 pieces",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "8g",
      carbs: "20g",
      fat: "8g",
      fiber: "4g",
    },
  },
  {
    id: 37,
    name: "Idli",
    type: "Breakfast",
    image:
      "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400&h=300&fit=crop&crop=center",
    price: 80,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 298,
    description: "Soft steamed rice cakes served with chutney and sambar",
    ingredients: ["Rice", "Urad dal", "Salt"],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "None",
    preparationTime: "10-15 mins",
    calories: 160,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    category: "South Indian",
    tags: ["Steamed", "Healthy", "Light"],
    allergens: ["None"],
    portion: "3 pieces",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "6g",
      carbs: "32g",
      fat: "1g",
      fiber: "2g",
    },
  },
  {
    id: 38,
    name: "Medu Vada",
    type: "Snack",
    image:
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop&crop=center",
    price: 70,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 189,
    description:
      "Traditional South Indian fried lentil donuts with hole in center",
    ingredients: ["Urad dal", "Ginger", "Curry leaves", "Black pepper", "Oil"],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "25-30 mins",
    calories: 200,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "South Indian",
    tags: ["Fried", "Traditional", "Crunchy"],
    allergens: ["None"],
    portion: "2 pieces",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "9g",
      carbs: "22g",
      fat: "9g",
      fiber: "4g",
    },
  },
  {
    id: 39,
    name: "Pongal",
    type: "Breakfast",
    image:
      "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop&crop=center",
    price: 110,
    originalPrice: null,
    rating: 4.0,
    reviewCount: 112,
    description: "Comforting rice and lentil porridge tempered with spices",
    ingredients: ["Rice", "Moong dal", "Ghee", "Black pepper", "Ginger"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "25-30 mins",
    calories: 280,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "South Indian",
    tags: ["Comfort food", "Porridge", "Traditional"],
    allergens: ["Dairy"],
    portion: "1 serving",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "12g",
      carbs: "48g",
      fat: "8g",
      fiber: "3g",
    },
  },
  {
    id: 40,
    name: "Upma",
    type: "Breakfast",
    image:
      "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop&crop=center",
    price: 90,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 145,
    description: "Savory semolina porridge with vegetables and spices",
    ingredients: [
      "Semolina",
      "Mixed vegetables",
      "Mustard seeds",
      "Curry leaves",
      "Ghee",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "15-20 mins",
    calories: 240,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "South Indian",
    tags: ["Quick", "Vegetables", "Light"],
    allergens: ["Dairy"],
    portion: "1 serving",
    chef: "Chef Venkatesh",
    nutritionalInfo: {
      protein: "6g",
      carbs: "45g",
      fat: "6g",
      fiber: "4g",
    },
  },
  {
    id: 41,
    name: "Sheer Chai",
    type: "Drink",
    image:
      "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop&crop=center",
    price: 40,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 78,
    description: "Traditional Kashmiri pink tea with cardamom and almonds",
    ingredients: ["Green tea", "Milk", "Cardamom", "Almonds", "Salt"],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "None",
    preparationTime: "10-15 mins",
    calories: 120,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Kashmiri",
    tags: ["Traditional", "Pink tea", "Aromatic"],
    allergens: ["Dairy", "Nuts"],
    portion: "1 cup",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "4g",
      carbs: "12g",
      fat: "6g",
      fiber: "0g",
    },
  },
  {
    id: 42,
    name: "Yakhni",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&h=300&fit=crop&crop=center",
    price: 380,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 89,
    description: "Kashmiri yogurt-based mutton curry with aromatic spices",
    ingredients: [
      "Mutton",
      "Yogurt",
      "Bay leaves",
      "Cardamom",
      "Fennel powder",
    ],
    dietary: ["Non-vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "60-70 mins",
    calories: 420,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Kashmiri",
    tags: ["Yogurt curry", "Aromatic", "Traditional"],
    allergens: ["Dairy"],
    portion: "1 serving",
    chef: "Chef Imran",
    nutritionalInfo: {
      protein: "32g",
      carbs: "8g",
      fat: "26g",
      fiber: "2g",
    },
  },
  {
    id: 43,
    name: "Dhokla",
    type: "Snack",
    image:
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop&crop=center",
    price: 80,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 167,
    description: "Steamed savory gram flour cake, spongy and tangy",
    ingredients: [
      "Gram flour",
      "Yogurt",
      "Ginger",
      "Green chilies",
      "Mustard seeds",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "25-30 mins",
    calories: 180,
    isAvailable: true,
    isRecommended: false,
    isPopular: true,
    category: "Gujarati",
    tags: ["Steamed", "Spongy", "Healthy"],
    allergens: ["Dairy"],
    portion: "4 pieces",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "8g",
      carbs: "28g",
      fat: "4g",
      fiber: "5g",
    },
  },
  {
    id: 44,
    name: "Khandvi",
    type: "Snack",
    image:
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop&crop=center",
    price: 120,
    originalPrice: null,
    rating: 4.5,
    reviewCount: 134,
    description:
      "Rolled gram flour sheets seasoned with mustard and sesame seeds",
    ingredients: [
      "Gram flour",
      "Yogurt",
      "Ginger paste",
      "Mustard seeds",
      "Sesame seeds",
    ],
    dietary: ["Vegetarian", "Gluten-free"],
    spiceLevel: "Mild",
    preparationTime: "35-40 mins",
    calories: 160,
    isAvailable: true,
    isRecommended: true,
    isPopular: false,
    category: "Gujarati",
    tags: ["Rolled", "Delicate", "Skillful"],
    allergens: ["Dairy"],
    portion: "6 rolls",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "8g",
      carbs: "22g",
      fat: "5g",
      fiber: "4g",
    },
  },
  {
    id: 45,
    name: "Undhiyu",
    type: "Main",
    image:
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop&crop=center",
    price: 200,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 98,
    description: "Mixed vegetable curry with winter vegetables and spices",
    ingredients: [
      "Mixed vegetables",
      "Methi muthiya",
      "Coconut",
      "Jaggery",
      "Spices",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-free"],
    spiceLevel: "Medium",
    preparationTime: "45-50 mins",
    calories: 280,
    isAvailable: false,
    isRecommended: false,
    isPopular: false,
    category: "Gujarati",
    tags: ["Winter special", "Mixed vegetables", "Festive"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "8g",
      carbs: "45g",
      fat: "8g",
      fiber: "12g",
    },
  },
  {
    id: 46,
    name: "Thepla",
    type: "Bread",
    image:
      "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop&crop=center",
    price: 60,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 123,
    description: "Spiced flatbread with fenugreek leaves, perfect for travel",
    ingredients: ["Wheat flour", "Fenugreek leaves", "Yogurt", "Spices", "Oil"],
    dietary: ["Vegetarian"],
    spiceLevel: "Mild",
    preparationTime: "20-25 mins",
    calories: 220,
    isAvailable: true,
    isRecommended: false,
    isPopular: false,
    category: "Gujarati",
    tags: ["Winter special", "Mixed vegetables", "Festive"],
    allergens: ["None"],
    portion: "1 serving",
    chef: "Chef Priya",
    nutritionalInfo: {
      protein: "8g",
      carbs: "45g",
      fat: "8g",
      fiber: "12g",
    },
  },
];

export const categories = [
  "Breakfast",
  "Main",
  "Seafood",
  "Snack",
  "Dessert",
  "Side Dish",
  "Drink",
  "Bread",
];

export const cuisineTypes = [
  "South Indian",
  "North Indian",
  "Kerala Special",
  "Punjabi",
  "Gujarati",
  "Bengali",
  "Goan",
];

export const dietaryFilters = [
  "Vegetarian",
  "Non-vegetarian",
  "Vegan",
  "Gluten-free",
  "Dairy-free",
  "Jain",
];

export const spiceLevels = ["Mild", "Medium", "Hot", "Very Hot"];
